// Curated "Frase da IA" question bank: each question's hex IS the round's
// secret color (converted to HSL), so the AI phrase and the color to guess
// are actually linked — unlike the old generic AI_PHRASE_BANK fallback.
// Keyed by LOBBY_THEMES id (shared/gameData.ts).

export type AiDifficulty = 'facil' | 'media' | 'dificil';

export interface AiQuestion {
  id: number;
  dificuldade: AiDifficulty;
  pergunta: string;
  hex: string;
}

export const AI_QUESTIONS: Record<string, AiQuestion[]> = {
  clash: [
    { id: 1, dificuldade: 'facil', pergunta: 'Qual é a cor da armadura dourada do Príncipe?', hex: '#D9A62E' },
    { id: 2, dificuldade: 'facil', pergunta: 'Qual é a cor do cavalo do Príncipe?', hex: '#8A542E' },
    { id: 3, dificuldade: 'facil', pergunta: 'Qual é a cor da barba do Lenhador?', hex: '#6B3E22' },
    { id: 4, dificuldade: 'facil', pergunta: 'Qual é a cor da Fúria?', hex: '#A855F7' },
    { id: 5, dificuldade: 'facil', pergunta: 'Qual é a cor principal do cabelo do Mago?', hex: '#6B3FA0' },
    { id: 6, dificuldade: 'facil', pergunta: 'Qual é a cor das chamas da Bola de Fogo?', hex: '#FF6A00' },
    { id: 7, dificuldade: 'facil', pergunta: 'Qual é a cor do gelo do Feitiço de Gelo?', hex: '#8DEBFF' },
    { id: 8, dificuldade: 'facil', pergunta: 'Qual é a cor dos cabelos da Valquíria?', hex: '#E85D3F' },
    { id: 9, dificuldade: 'facil', pergunta: 'Qual é a cor da armadura do Cavaleiro?', hex: '#6E737A' },
    { id: 10, dificuldade: 'facil', pergunta: 'Qual é a cor do escudo do Príncipe das Trevas?', hex: '#252833' },
    { id: 11, dificuldade: 'facil', pergunta: 'Qual é a cor da pele dos Goblins?', hex: '#63B52D' },
    { id: 12, dificuldade: 'facil', pergunta: 'Qual é a cor da pele dos Goblins Lanceiros?', hex: '#6FBE35' },
    { id: 13, dificuldade: 'facil', pergunta: 'Qual é a cor da roupa do Goblin?', hex: '#4C8F26' },
    { id: 14, dificuldade: 'facil', pergunta: 'Qual é a cor do capacete do Mini P.E.K.K.A?', hex: '#5E6470' },
    { id: 15, dificuldade: 'facil', pergunta: 'Qual é a cor dos olhos do Mini P.E.K.K.A?', hex: '#35C8FF' },
    { id: 16, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo da Mosqueteira?', hex: '#6B3E24' },
    { id: 17, dificuldade: 'facil', pergunta: 'Qual é a cor do vestido da Mosqueteira?', hex: '#3D6FA8' },
    { id: 18, dificuldade: 'facil', pergunta: 'Qual é a cor da roupa da Princesa?', hex: '#E85C73' },
    { id: 19, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo da Princesa?', hex: '#8A4B2B' },
    { id: 20, dificuldade: 'facil', pergunta: 'Qual é a cor do fogo do Dragão Bebê?', hex: '#FF7A00' },
    { id: 21, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo do Dragão Bebê?', hex: '#75B82C' },
    { id: 22, dificuldade: 'facil', pergunta: 'Qual é a cor da capa do Mago de Gelo?', hex: '#3E7DB8' },
    { id: 23, dificuldade: 'facil', pergunta: 'Qual é a cor da pele do Esqueleto?', hex: '#E8E4D8' },
    { id: 24, dificuldade: 'facil', pergunta: 'Qual é a cor do fogo do Espírito de Fogo?', hex: '#FF8A00' },
    { id: 25, dificuldade: 'facil', pergunta: 'Qual é a cor do Espírito de Gelo?', hex: '#74DFFF' },
    { id: 26, dificuldade: 'facil', pergunta: 'Qual é a cor do Espírito Elétrico?', hex: '#4FCBFF' },
    { id: 27, dificuldade: 'facil', pergunta: 'Qual é a cor do raio do Espírito Elétrico?', hex: '#8BE9FF' },
    { id: 28, dificuldade: 'facil', pergunta: 'Qual é a cor da roupa do Lenhador?', hex: '#A52E2E' },
    { id: 29, dificuldade: 'facil', pergunta: 'Qual é a cor da barba do Gigante?', hex: '#C17A42' },
    { id: 30, dificuldade: 'facil', pergunta: 'Qual é a cor da pele do Gigante?', hex: '#E5A36D' },
    { id: 31, dificuldade: 'facil', pergunta: 'Qual é a cor da roupa do Príncipe das Trevas?', hex: '#242631' },
    { id: 32, dificuldade: 'facil', pergunta: 'Qual é a cor da capa da Bruxa?', hex: '#6A3D8F' },
    { id: 33, dificuldade: 'facil', pergunta: 'Qual é a cor dos olhos da Bruxa?', hex: '#D84AFF' },
    { id: 34, dificuldade: 'facil', pergunta: 'Qual é a cor dos cabelos da Bruxa?', hex: '#29202F' },
    { id: 35, dificuldade: 'facil', pergunta: 'Qual é a cor da roupa do Mago Elétrico?', hex: '#234A91' },
    { id: 36, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo do Mago Elétrico?', hex: '#E6D9C3' },
    { id: 37, dificuldade: 'facil', pergunta: 'Qual é a cor do raio do Mago Elétrico?', hex: '#6DDCFF' },
    { id: 38, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo do Balão?', hex: '#A83232' },
    { id: 39, dificuldade: 'facil', pergunta: 'Qual é a cor da cesta do Balão?', hex: '#9A632E' },
    { id: 40, dificuldade: 'facil', pergunta: 'Qual é a cor do fogo da Torre Inferno?', hex: '#FF5A00' },
    { id: 41, dificuldade: 'facil', pergunta: 'Qual é a cor principal do Dragão Infernal?', hex: '#4D2923' },
    { id: 42, dificuldade: 'facil', pergunta: 'Qual é a cor do fogo do Dragão Infernal?', hex: '#FF5B16' },
    { id: 43, dificuldade: 'facil', pergunta: 'Qual é a cor da armadura do Mega Cavaleiro?', hex: '#292D3A' },
    { id: 44, dificuldade: 'facil', pergunta: 'Qual é a cor dos olhos do Mega Cavaleiro?', hex: '#FF5A3D' },
    { id: 45, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo do Rei?', hex: '#7A4A2B' },
    { id: 46, dificuldade: 'facil', pergunta: 'Qual é a cor da coroa do Rei?', hex: '#F5C542' },
    { id: 47, dificuldade: 'facil', pergunta: 'Qual é a cor da camisa do Rei?', hex: '#3E75B6' },
    { id: 48, dificuldade: 'facil', pergunta: 'Qual é a cor do elixir?', hex: '#D946EF' },
    { id: 49, dificuldade: 'facil', pergunta: 'Qual é a cor da água do rio da Arena?', hex: '#3DB7D9' },
    { id: 50, dificuldade: 'facil', pergunta: 'Qual é a cor das Torres da Coroa?', hex: '#D8A23A' },
    { id: 51, dificuldade: 'media', pergunta: 'Qual é a cor da ponta da lança do Príncipe?', hex: '#DCE8F2' },
    { id: 52, dificuldade: 'media', pergunta: 'Qual é a cor da faixa azul do Príncipe?', hex: '#3975C6' },
    { id: 53, dificuldade: 'media', pergunta: 'Qual é a cor do pelo mais claro do cavalo do Príncipe?', hex: '#A96B3B' },
    { id: 54, dificuldade: 'media', pergunta: 'Qual é a cor do machado do Lenhador?', hex: '#8C9198' },
    { id: 55, dificuldade: 'media', pergunta: 'Qual é a cor da camisa do Lenhador?', hex: '#B83B3B' },
    { id: 56, dificuldade: 'media', pergunta: 'Qual é a cor do frasco de Fúria?', hex: '#7D3DB8' },
    { id: 57, dificuldade: 'media', pergunta: 'Qual é a cor do brilho ao redor da Fúria?', hex: '#D66CFF' },
    { id: 58, dificuldade: 'media', pergunta: 'Qual é a cor central da Bola de Fogo?', hex: '#FFD23F' },
    { id: 59, dificuldade: 'media', pergunta: 'Qual é a cor da borda das chamas da Bola de Fogo?', hex: '#E83B00' },
    { id: 60, dificuldade: 'media', pergunta: 'Qual é a cor da fumaça deixada pelo Feitiço de Gelo?', hex: '#C8F6FF' },
    { id: 61, dificuldade: 'media', pergunta: 'Qual é a cor da máscara do Príncipe das Trevas?', hex: '#161820' },
    { id: 62, dificuldade: 'media', pergunta: 'Qual é a cor do detalhe dourado do escudo do Príncipe das Trevas?', hex: '#C99A32' },
    { id: 63, dificuldade: 'media', pergunta: 'Qual é a cor do cabelo da Arqueira?', hex: '#8A542D' },
    { id: 64, dificuldade: 'media', pergunta: 'Qual é a cor da roupa da Arqueira?', hex: '#D95A8A' },
    { id: 65, dificuldade: 'media', pergunta: 'Qual é a cor das flechas das Arqueiras?', hex: '#C49A5A' },
    { id: 66, dificuldade: 'media', pergunta: 'Qual é a cor da armadura do P.E.K.K.A?', hex: '#303746' },
    { id: 67, dificuldade: 'media', pergunta: 'Qual é a cor dos olhos do P.E.K.K.A?', hex: '#C93AFF' },
    { id: 68, dificuldade: 'media', pergunta: 'Qual é a cor do fogo nos olhos do P.E.K.K.A?', hex: '#8B2CFF' },
    { id: 69, dificuldade: 'media', pergunta: 'Qual é a cor da roupa da Bandida?', hex: '#5A4B70' },
    { id: 70, dificuldade: 'media', pergunta: 'Qual é a cor da máscara da Bandida?', hex: '#2B2634' },
    { id: 71, dificuldade: 'media', pergunta: 'Qual é a cor do efeito do dash da Bandida?', hex: '#B8A5FF' },
    { id: 72, dificuldade: 'media', pergunta: 'Qual é a cor do cabelo do Cavaleiro Dourado?', hex: '#C98B3A' },
    { id: 73, dificuldade: 'media', pergunta: 'Qual é a cor da armadura do Cavaleiro Dourado?', hex: '#E3B84A' },
    { id: 74, dificuldade: 'media', pergunta: 'Qual é a cor do brilho da habilidade do Cavaleiro Dourado?', hex: '#FFD75A' },
    { id: 75, dificuldade: 'media', pergunta: 'Qual é a cor da capa do Mago?', hex: '#7436A5' },
    { id: 76, dificuldade: 'media', pergunta: 'Qual é a cor do cinto do Mago?', hex: '#E6A72F' },
    { id: 77, dificuldade: 'media', pergunta: 'Qual é a cor das faíscas do Mago Elétrico?', hex: '#69D9FF' },
    { id: 78, dificuldade: 'media', pergunta: 'Qual é a cor do raio do Dragão Infernal quando está carregando?', hex: '#FF9D24' },
    { id: 79, dificuldade: 'media', pergunta: 'Qual é a cor do brilho mais intenso no centro do raio do Dragão Infernal?', hex: '#FFE15C' },
    { id: 80, dificuldade: 'media', pergunta: 'Qual é a cor do fogo da Torre Inferno quando está totalmente carregada?', hex: '#FF2D00' },
    { id: 81, dificuldade: 'dificil', pergunta: 'Qual é a cor do centro do raio do Dragão Infernal no estágio máximo?', hex: '#FFF19A' },
    { id: 82, dificuldade: 'dificil', pergunta: 'Qual é a cor da borda externa do raio do Dragão Infernal?', hex: '#FF4A00' },
    { id: 83, dificuldade: 'dificil', pergunta: 'Qual é a cor da chama refletida na armadura do Dragão Infernal?', hex: '#FF7133' },
    { id: 84, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho do ataque carregado da Torre Inferno?', hex: '#FF7B00' },
    { id: 85, dificuldade: 'dificil', pergunta: 'Qual é a cor mais clara no centro da explosão da Bola de Fogo?', hex: '#FFF0A3' },
    { id: 86, dificuldade: 'dificil', pergunta: 'Qual é a cor mais escura da fumaça da Bola de Fogo?', hex: '#7A1D0A' },
    { id: 87, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho no centro do efeito da Fúria?', hex: '#E7A1FF' },
    { id: 88, dificuldade: 'dificil', pergunta: 'Qual é a cor da região mais escura do círculo da Fúria?', hex: '#632080' },
    { id: 89, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho do ataque do Mago Elétrico?', hex: '#D8F8FF' },
    { id: 90, dificuldade: 'dificil', pergunta: 'Qual é a cor mais intensa do raio do Mago Elétrico?', hex: '#39C8FF' },
    { id: 91, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho do ataque da Princesa?', hex: '#FFB7C8' },
    { id: 92, dificuldade: 'dificil', pergunta: 'Qual é a cor da chama do Dragão Bebê imediatamente antes da explosão?', hex: '#FFD33D' },
    { id: 93, dificuldade: 'dificil', pergunta: 'Qual é a cor da parte mais escura da armadura do P.E.K.K.A?', hex: '#171A24' },
    { id: 94, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho roxo dos olhos do P.E.K.K.A?', hex: '#B72CFF' },
    { id: 95, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho do ataque do Príncipe quando ele está em carga?', hex: '#D9E8FF' },
    { id: 96, dificuldade: 'dificil', pergunta: 'Qual é a cor do detalhe mais claro da armadura dourada do Príncipe?', hex: '#FFE37A' },
    { id: 97, dificuldade: 'dificil', pergunta: 'Qual é a cor da sombra mais escura da barba do Lenhador?', hex: '#3D2116' },
    { id: 98, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho produzido pelo ataque do Cavaleiro Dourado?', hex: '#FFF0A0' },
    { id: 99, dificuldade: 'dificil', pergunta: 'Qual é a cor da energia do ataque do Espírito Elétrico no momento do impacto?', hex: '#B5F5FF' },
    { id: 100, dificuldade: 'dificil', pergunta: 'Qual é a cor do centro luminoso da explosão do Relâmpago?', hex: '#F4F8FF' },
  ],
  marvel: [
    { id: 1, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da armadura do Homem de Ferro?', hex: '#B71C1C' },
    { id: 2, dificuldade: 'facil', pergunta: 'Qual é a cor predominante das partes metálicas douradas da armadura do Homem de Ferro?', hex: '#D4A72C' },
    { id: 3, dificuldade: 'facil', pergunta: 'Qual é a cor do reator no peito do Homem de Ferro?', hex: '#8DEBFF' },
    { id: 4, dificuldade: 'facil', pergunta: 'Qual é a cor dos olhos da armadura do Homem de Ferro?', hex: '#B8F3FF' },
    { id: 5, dificuldade: 'facil', pergunta: 'Qual é a cor das faixas externas do escudo do Capitão América?', hex: '#C62828' },
    { id: 6, dificuldade: 'facil', pergunta: 'Qual é a cor do círculo que fica ao redor da estrela no escudo do Capitão América?', hex: '#174A8B' },
    { id: 7, dificuldade: 'facil', pergunta: 'Qual é a cor da estrela no centro do escudo do Capitão América?', hex: '#F2F2F2' },
    { id: 8, dificuldade: 'facil', pergunta: 'Qual é a cor da pele do Hulk?', hex: '#4CAF50' },
    { id: 9, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo do Hulk?', hex: '#181818' },
    { id: 10, dificuldade: 'facil', pergunta: 'Qual é a cor da calça do Hulk?', hex: '#6A1B9A' },
    { id: 11, dificuldade: 'facil', pergunta: 'Qual é a cor do martelo de Thor?', hex: '#8D969D' },
    { id: 12, dificuldade: 'facil', pergunta: 'Qual é a cor da capa de Thor?', hex: '#8B0000' },
    { id: 13, dificuldade: 'facil', pergunta: 'Qual é a cor dos raios produzidos por Thor?', hex: '#DDF7FF' },
    { id: 14, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do uniforme do Homem-Aranha?', hex: '#C62828' },
    { id: 15, dificuldade: 'facil', pergunta: 'Qual é a cor predominante das áreas laterais do uniforme clássico do Homem-Aranha?', hex: '#1565C0' },
    { id: 16, dificuldade: 'facil', pergunta: 'Qual é a cor das lentes da máscara do Homem-Aranha?', hex: '#F4F4F4' },
    { id: 17, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do uniforme da Viúva Negra?', hex: '#171717' },
    { id: 18, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do cabelo da Viúva Negra em Os Vingadores?', hex: '#B34A35' },
    { id: 19, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa do Gavião Arqueiro em Os Vingadores?', hex: '#25282D' },
    { id: 20, dificuldade: 'facil', pergunta: 'Qual é a cor da haste das flechas do Gavião Arqueiro?', hex: '#8B5A2B' },
    { id: 21, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da capa do Doutor Estranho?', hex: '#9E1B32' },
    { id: 22, dificuldade: 'facil', pergunta: 'Qual é a cor dos efeitos dos portais criados pelo Doutor Estranho?', hex: '#F5A623' },
    { id: 23, dificuldade: 'facil', pergunta: 'Qual é a cor da energia utilizada pela Feiticeira Escarlate?', hex: '#D41446' },
    { id: 24, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do traje do Pantera Negra?', hex: '#111111' },
    { id: 25, dificuldade: 'facil', pergunta: 'Qual é a cor das linhas luminosas do traje do Pantera Negra?', hex: '#5B4B9A' },
    { id: 26, dificuldade: 'facil', pergunta: 'Qual é a cor da pele da Gamora?', hex: '#4CAF50' },
    { id: 27, dificuldade: 'facil', pergunta: 'Qual é a cor da pele do Drax?', hex: '#78909C' },
    { id: 28, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo do Groot?', hex: '#795548' },
    { id: 29, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do pelo do Rocket?', hex: '#8D6748' },
    { id: 30, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da jaqueta do Senhor das Estrelas?', hex: '#263238' },
    { id: 31, dificuldade: 'facil', pergunta: 'Qual é a cor da pele do Thanos?', hex: '#6A3D9A' },
    { id: 32, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da armadura de Thanos?', hex: '#5D4A3A' },
    { id: 33, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da Manopla do Infinito?', hex: '#C9A227' },
    { id: 34, dificuldade: 'facil', pergunta: 'Qual é a cor da Joia que fica dentro do Tesseract?', hex: '#29B6F6' },
    { id: 35, dificuldade: 'facil', pergunta: 'Qual é a cor da Joia que estava no cetro de Loki?', hex: '#FFD740' },
    { id: 36, dificuldade: 'facil', pergunta: 'Qual é a cor da Joia utilizada por Ronan?', hex: '#7B1FA2' },
    { id: 37, dificuldade: 'facil', pergunta: 'Qual é a cor da Joia usada pelo Doutor Estranho para manipular o tempo?', hex: '#43A047' },
    { id: 38, dificuldade: 'facil', pergunta: 'Qual é a cor da Joia usada por Thanos para alterar a realidade?', hex: '#D32F2F' },
    { id: 39, dificuldade: 'facil', pergunta: 'Qual é a cor da Joia encontrada em Vormir?', hex: '#FF9800' },
    { id: 40, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do uniforme de Loki?', hex: '#1B5E20' },
    { id: 41, dificuldade: 'facil', pergunta: 'Qual é a cor dos chifres do capacete de Loki?', hex: '#C9A227' },
    { id: 42, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do uniforme da Capitã Marvel?', hex: '#0D47A1' },
    { id: 43, dificuldade: 'facil', pergunta: 'Qual é a cor do símbolo no peito da Capitã Marvel?', hex: '#E0B51A' },
    { id: 44, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do traje do Homem-Formiga?', hex: '#B71C1C' },
    { id: 45, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do traje da Vespa?', hex: '#D9A514' },
    { id: 46, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do uniforme do Soldado Invernal?', hex: '#455A64' },
    { id: 47, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do uniforme do Falcão?', hex: '#20252A' },
    { id: 48, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo do Visão?', hex: '#B52B2B' },
    { id: 49, dificuldade: 'facil', pergunta: 'Qual é a cor da Joia que aparece na testa do Visão?', hex: '#F6D94A' },
    { id: 50, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da armadura do Máquina de Combate?', hex: '#4A4F55' },
    { id: 51, dificuldade: 'media', pergunta: 'Qual é a cor do brilho do reator Arc do Homem de Ferro quando ele está totalmente carregado?', hex: '#A8F3FF' },
    { id: 52, dificuldade: 'media', pergunta: 'Qual é a cor predominante das placas metálicas da Mark 42?', hex: '#C99A2E' },
    { id: 53, dificuldade: 'media', pergunta: 'Qual é a cor predominante da armadura Hulkbuster?', hex: '#8A1F1F' },
    { id: 54, dificuldade: 'media', pergunta: 'Qual é a cor das luzes dos olhos da Hulkbuster?', hex: '#8BE9FF' },
    { id: 55, dificuldade: 'media', pergunta: 'Qual é a cor predominante do uniforme usado por Steve Rogers em O Soldado Invernal?', hex: '#1E3A5F' },
    { id: 56, dificuldade: 'media', pergunta: 'Qual é a cor da estrela no peito do uniforme usado por Steve Rogers em O Soldado Invernal?', hex: '#D9DDE2' },
    { id: 57, dificuldade: 'media', pergunta: 'Qual é a cor predominante da armadura de Thor em Ragnarok?', hex: '#37474F' },
    { id: 58, dificuldade: 'media', pergunta: 'Qual é a cor predominante da armadura usada por Hela?', hex: '#181818' },
    { id: 59, dificuldade: 'media', pergunta: 'Qual é a cor do brilho das armas criadas por Hela?', hex: '#43A047' },
    { id: 60, dificuldade: 'media', pergunta: 'Qual é a cor predominante do Bifrost quando ele está ativo?', hex: '#6DD5FF' },
    { id: 61, dificuldade: 'media', pergunta: 'Qual é a cor predominante das teias disparadas pelo Homem-Aranha?', hex: '#E1E5E8' },
    { id: 62, dificuldade: 'media', pergunta: 'Qual é a cor das lentes do traje Aranha de Ferro?', hex: '#63D8FF' },
    { id: 63, dificuldade: 'media', pergunta: 'Qual é a cor predominante das pernas mecânicas do traje Aranha de Ferro?', hex: '#B71C1C' },
    { id: 64, dificuldade: 'media', pergunta: 'Qual é a cor predominante do traje usado pelo Homem-Aranha durante sua missão em Berlim?', hex: '#111318' },
    { id: 65, dificuldade: 'media', pergunta: 'Qual é a cor das faíscas produzidas pelos feitiços do Doutor Estranho?', hex: '#FFAA2B' },
    { id: 66, dificuldade: 'media', pergunta: 'Qual é a cor predominante das páginas do Darkhold?', hex: '#30201E' },
    { id: 67, dificuldade: 'media', pergunta: 'Qual é a cor do brilho mágico usado por Wanda em Multiverso da Loucura?', hex: '#D41446' },
    { id: 68, dificuldade: 'media', pergunta: 'Qual é a cor predominante do traje de batalha da Feiticeira Escarlate?', hex: '#8E1027' },
    { id: 69, dificuldade: 'media', pergunta: 'Qual é a cor predominante do capacete de Mysterio?', hex: '#2F3437' },
    { id: 70, dificuldade: 'media', pergunta: 'Qual é a cor predominante das ilusões criadas por Mysterio?', hex: '#4CAF50' },
    { id: 71, dificuldade: 'media', pergunta: 'Qual é a cor predominante do traje de Killmonger durante a batalha final?', hex: '#151515' },
    { id: 72, dificuldade: 'media', pergunta: 'Qual é a cor predominante das linhas luminosas do traje do Pantera Negra durante a batalha?', hex: '#6B55A5' },
    { id: 73, dificuldade: 'media', pergunta: 'Qual é a cor do brilho produzido pelo traje do Pantera Negra ao absorver impactos?', hex: '#7E57C2' },
    { id: 74, dificuldade: 'media', pergunta: 'Qual é a cor predominante do traje usado por Shuri quando assume o manto do Pantera Negra?', hex: '#111111' },
    { id: 75, dificuldade: 'media', pergunta: 'Qual é a cor predominante da armadura do Homem-Formiga?', hex: '#9E1B24' },
    { id: 76, dificuldade: 'media', pergunta: 'Qual é a cor das partículas liberadas pelos equipamentos de Hank Pym?', hex: '#E8B52E' },
    { id: 77, dificuldade: 'media', pergunta: 'Qual é a cor predominante do traje de batalha do Senhor das Estrelas?', hex: '#263238' },
    { id: 78, dificuldade: 'media', pergunta: 'Qual é a cor da energia disparada pelos blasters do Senhor das Estrelas?', hex: '#FFB52E' },
    { id: 79, dificuldade: 'media', pergunta: 'Qual é a cor predominante da roupa de batalha da Gamora?', hex: '#20242A' },
    { id: 80, dificuldade: 'media', pergunta: 'Qual é a cor predominante da armadura de Thanos durante a batalha em Wakanda?', hex: '#5C4738' },
    { id: 81, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho no centro do Tesseract quando ele é ativado?', hex: '#9BEFFF' },
    { id: 82, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho emitido pelo cetro de Loki quando seu poder é utilizado?', hex: '#FFE45C' },
    { id: 83, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho que envolve a Joia do Tempo quando o Doutor Estranho a utiliza?', hex: '#7BCB3A' },
    { id: 84, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho produzido pela Joia do Poder quando Ronan utiliza seu poder?', hex: '#8E24AA' },
    { id: 85, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho produzido pela Joia da Realidade quando Thanos altera a matéria?', hex: '#D32F2F' },
    { id: 86, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho associado à Joia da Alma em Vormir?', hex: '#FF8C00' },
    { id: 87, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante das faíscas usadas pelo Doutor Estranho para abrir um portal?', hex: '#F6A623' },
    { id: 88, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho das duplicações mágicas criadas pelo Doutor Estranho?', hex: '#FFB52E' },
    { id: 89, dificuldade: 'dificil', pergunta: 'Qual é a cor mais intensa da energia utilizada por Wanda contra Thanos?', hex: '#FF1744' },
    { id: 90, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho da energia utilizada por Wanda para destruir o Darkhold?', hex: '#D5003D' },
    { id: 91, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho que aparece ao redor do Homem-Aranha quando seu sentido-aranha é representado visualmente?', hex: '#FFD54F' },
    { id: 92, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante das partículas luminosas do Reino Quântico?', hex: '#7E57C2' },
    { id: 93, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da energia liberada pela Capitã Marvel quando seus poderes estão no máximo?', hex: '#64D8FF' },
    { id: 94, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho que aparece nos olhos da Capitã Marvel quando seus poderes estão ativos?', hex: '#A8F0FF' },
    { id: 95, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da energia que envolve Thanos quando ele utiliza várias Joias do Infinito?', hex: '#B56CFF' },
    { id: 96, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho produzido no momento em que Thanos realiza o estalo?', hex: '#FFF1B8' },
    { id: 97, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho que percorre a Manopla do Infinito durante o estalo?', hex: '#C084FC' },
    { id: 98, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da energia que percorre a armadura de Tony Stark quando ele utiliza as Joias do Infinito?', hex: '#FFD54F' },
    { id: 99, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho que aparece na armadura de Tony Stark após utilizar as Joias do Infinito?', hex: '#FFB74D' },
    { id: 100, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da energia liberada pelo ataque final de Thor contra Thanos?', hex: '#DDF7FF' },
  ],
  disney: [
    { id: 1, dificuldade: 'facil', pergunta: 'Qual é a cor da juba de Simba quando adulto?', hex: '#8B542F' },
    { id: 2, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo de Simba?', hex: '#D99A3D' },
    { id: 3, dificuldade: 'facil', pergunta: 'Qual é a cor do pelo de Timão?', hex: '#C98B52' },
    { id: 4, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo de Pumba?', hex: '#9B6A52' },
    { id: 5, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Rafiki?', hex: '#8A8C91' },
    { id: 6, dificuldade: 'facil', pergunta: 'Qual é a cor da roupa de Aladdin?', hex: '#6C4AA0' },
    { id: 7, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo do Gênio?', hex: '#1685A8' },
    { id: 8, dificuldade: 'facil', pergunta: 'Qual é a cor do vestido de Jasmine?', hex: '#55C7C9' },
    { id: 9, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do tapete mágico?', hex: '#B52D32' },
    { id: 10, dificuldade: 'facil', pergunta: 'Qual é a cor da roupa de Jafar?', hex: '#5B2148' },
    { id: 11, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo de Ariel?', hex: '#B93632' },
    { id: 12, dificuldade: 'facil', pergunta: 'Qual é a cor da cauda de Ariel?', hex: '#20A88A' },
    { id: 13, dificuldade: 'facil', pergunta: 'Qual é a cor do top de Ariel?', hex: '#7B4AA0' },
    { id: 14, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo de Sebastião?', hex: '#D93632' },
    { id: 15, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo de Linguado?', hex: '#F2D34F' },
    { id: 16, dificuldade: 'facil', pergunta: 'Qual é a cor do vestido de Bela no baile?', hex: '#F2C84B' },
    { id: 17, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da pelagem da Fera?', hex: '#7B563F' },
    { id: 18, dificuldade: 'facil', pergunta: 'Qual é a cor da rosa encantada?', hex: '#C92D3F' },
    { id: 19, dificuldade: 'facil', pergunta: 'Qual é a cor da xícara de Chip?', hex: '#E8E2D2' },
    { id: 20, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Mulan no início do filme?', hex: '#D85A75' },
    { id: 21, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo de Mushu?', hex: '#D53A2F' },
    { id: 22, dificuldade: 'facil', pergunta: 'Qual é a cor das escamas de Mushu?', hex: '#E0A52F' },
    { id: 23, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo de Hércules?', hex: '#D79A42' },
    { id: 24, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Hércules?', hex: '#6B82A8' },
    { id: 25, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo de Hades?', hex: '#2D8C8B' },
    { id: 26, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Tarzan?', hex: '#6E9B49' },
    { id: 27, dificuldade: 'facil', pergunta: 'Qual é a cor do pelo de Kala?', hex: '#5D5148' },
    { id: 28, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do vestido de Pocahontas?', hex: '#A56A4C' },
    { id: 29, dificuldade: 'facil', pergunta: 'Qual é a cor do pelo de Meeko?', hex: '#6D5140' },
    { id: 30, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Kuzco?', hex: '#7A3E91' },
    { id: 31, dificuldade: 'facil', pergunta: 'Qual é a cor do pelo de Kronk?', hex: '#D6A03A' },
    { id: 32, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo de Stitch?', hex: '#4C8DCC' },
    { id: 33, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Lilo?', hex: '#D9363E' },
    { id: 34, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do pelo de Kenai como urso?', hex: '#7B4F32' },
    { id: 35, dificuldade: 'facil', pergunta: 'Qual é a cor do vestido de Tiana?', hex: '#76B852' },
    { id: 36, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do traje do Dr. Facilier?', hex: '#25203A' },
    { id: 37, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo de Rapunzel?', hex: '#D9A441' },
    { id: 38, dificuldade: 'facil', pergunta: 'Qual é a cor do vestido de Rapunzel?', hex: '#A56BB5' },
    { id: 39, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo de Pascal?', hex: '#69A84F' },
    { id: 40, dificuldade: 'facil', pergunta: 'Qual é a cor do vestido de Elsa?', hex: '#8ED8E8' },
    { id: 41, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo de Elsa?', hex: '#D7D7E4' },
    { id: 42, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Anna?', hex: '#7A3159' },
    { id: 43, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo de Olaf?', hex: '#F1EEE5' },
    { id: 44, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Moana?', hex: '#C65B3C' },
    { id: 45, dificuldade: 'facil', pergunta: 'Qual é a cor da pele de Maui?', hex: '#6D412F' },
    { id: 46, dificuldade: 'facil', pergunta: 'Qual é a cor dos óculos de Mirabel?', hex: '#6B4A35' },
    { id: 47, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do vestido de Mirabel?', hex: '#6A3C78' },
    { id: 48, dificuldade: 'facil', pergunta: 'Qual é a cor do pelo de Judy Hopps?', hex: '#B7B9B1' },
    { id: 49, dificuldade: 'facil', pergunta: 'Qual é a cor do pelo de Nick Wilde?', hex: '#C56A3A' },
    { id: 50, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Ralph?', hex: '#7A4B35' },
    { id: 51, dificuldade: 'media', pergunta: 'Qual é a cor predominante do uniforme de Woody?', hex: '#D8B43A' },
    { id: 52, dificuldade: 'media', pergunta: 'Qual é a cor do lenço de Woody?', hex: '#8C2026' },
    { id: 53, dificuldade: 'media', pergunta: 'Qual é a cor predominante do traje de Buzz Lightyear?', hex: '#E8E8DF' },
    { id: 54, dificuldade: 'media', pergunta: 'Qual é a cor das asas de Buzz Lightyear?', hex: '#7BB8A0' },
    { id: 55, dificuldade: 'media', pergunta: 'Qual é a cor do corpo de Sulley?', hex: '#4D9AB5' },
    { id: 56, dificuldade: 'media', pergunta: 'Qual é a cor das manchas do corpo de Sulley?', hex: '#A66BB7' },
    { id: 57, dificuldade: 'media', pergunta: 'Qual é a cor do corpo de Mike Wazowski?', hex: '#75B943' },
    { id: 58, dificuldade: 'media', pergunta: 'Qual é a cor predominante do corpo de Nemo?', hex: '#F07832' },
    { id: 59, dificuldade: 'media', pergunta: 'Qual é a cor das listras do corpo de Nemo?', hex: '#F2F0E8' },
    { id: 60, dificuldade: 'media', pergunta: 'Qual é a cor predominante do corpo de Dory?', hex: '#2385C5' },
    { id: 61, dificuldade: 'media', pergunta: 'Qual é a cor predominante do uniforme do Sr. Incrível?', hex: '#D72F2F' },
    { id: 62, dificuldade: 'media', pergunta: 'Qual é a cor da máscara do Sr. Incrível?', hex: '#F0A52B' },
    { id: 63, dificuldade: 'media', pergunta: 'Qual é a cor predominante do uniforme da Mulher-Elástica?', hex: '#D72F2F' },
    { id: 64, dificuldade: 'media', pergunta: 'Qual é a cor predominante do uniforme do Gelado?', hex: '#6FB9D6' },
    { id: 65, dificuldade: 'media', pergunta: 'Qual é a cor do corpo de Relâmpago McQueen?', hex: '#D92727' },
    { id: 66, dificuldade: 'media', pergunta: 'Qual é a cor do corpo de Mate?', hex: '#A66A3F' },
    { id: 67, dificuldade: 'media', pergunta: 'Qual é a cor do pelo de Remy?', hex: '#8A6A54' },
    { id: 68, dificuldade: 'media', pergunta: 'Qual é a cor predominante do corpo de WALL-E?', hex: '#B08A3C' },
    { id: 69, dificuldade: 'media', pergunta: 'Qual é a cor predominante da casa de Carl?', hex: '#D3A34A' },
    { id: 70, dificuldade: 'media', pergunta: 'Qual é a cor dos balões presos à casa de Carl?', hex: '#E64B45' },
    { id: 71, dificuldade: 'media', pergunta: 'Qual é a cor do cabelo de Merida?', hex: '#D45A25' },
    { id: 72, dificuldade: 'media', pergunta: 'Qual é a cor predominante do vestido de Merida?', hex: '#315B48' },
    { id: 73, dificuldade: 'media', pergunta: 'Qual é a cor do corpo de Mike Wazowski?', hex: '#78B943' },
    { id: 74, dificuldade: 'media', pergunta: 'Qual é a cor predominante do pelo de Sulley?', hex: '#4C8FB1' },
    { id: 75, dificuldade: 'media', pergunta: 'Qual é a cor do corpo de Alegria?', hex: '#F4C62E' },
    { id: 76, dificuldade: 'media', pergunta: 'Qual é a cor do corpo de Tristeza?', hex: '#416FC1' },
    { id: 77, dificuldade: 'media', pergunta: 'Qual é a cor do corpo de Raiva?', hex: '#D83A2E' },
    { id: 78, dificuldade: 'media', pergunta: 'Qual é a cor do corpo de Nojinho?', hex: '#65B64A' },
    { id: 79, dificuldade: 'media', pergunta: 'Qual é a cor predominante da roupa de Miguel?', hex: '#E8E0D3' },
    { id: 80, dificuldade: 'media', pergunta: 'Qual é a cor predominante da pele de Héctor?', hex: '#D5A15C' },
    { id: 81, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da juba de Scar?', hex: '#30251F' },
    { id: 82, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do traje de dança usado por Jasmine?', hex: '#49B9B8' },
    { id: 83, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do vestido de Ursula?', hex: '#33254D' },
    { id: 84, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante das roupas de Gaston?', hex: '#304F85' },
    { id: 85, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da armadura usada pelos soldados chineses?', hex: '#5A6470' },
    { id: 86, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da chama que envolve Hades?', hex: '#42A8A0' },
    { id: 87, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do traje de Stitch quando ele está disfarçado de Elvis?', hex: '#1B2638' },
    { id: 88, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante das sombras mágicas do Dr. Facilier?', hex: '#241B36' },
    { id: 89, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante das lanternas lançadas no céu?', hex: '#F4A13A' },
    { id: 90, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do castelo de gelo de Elsa?', hex: '#8FD8EA' },
    { id: 91, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do coração de Te Fiti?', hex: '#6FCB63' },
    { id: 92, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da lava de Te Kā?', hex: '#D94A32' },
    { id: 93, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante das flores criadas por Isabela?', hex: '#D64D9A' },
    { id: 94, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do vestido de Isabela?', hex: '#C56BC5' },
    { id: 95, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do uniforme policial de Judy?', hex: '#4E83A5' },
    { id: 96, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do traje de Jessie?', hex: '#D94B35' },
    { id: 97, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da porta do quarto de Boo?', hex: '#D86A94' },
    { id: 98, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do símbolo no peito dos Incríveis?', hex: '#F0A52B' },
    { id: 99, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante das ilhas de personalidade de Riley?', hex: '#6D5AA8' },
    { id: 100, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante das flores que formam a ponte entre os mundos?', hex: '#F2A63B' },
  ],
  futebol: [
    { id: 1, dificuldade: 'facil', pergunta: 'Qual é a cor predominante das letras no escudo do Flamengo?', hex: '#000000' },
    { id: 2, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do círculo externo do escudo do Corinthians?', hex: '#000000' },
    { id: 3, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do círculo externo do escudo do Palmeiras?', hex: '#006437' },
    { id: 4, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da faixa central do escudo do São Paulo?', hex: '#E31B23' },
    { id: 5, dificuldade: 'facil', pergunta: 'Qual é a cor predominante das faixas verticais do escudo do Santos?', hex: '#000000' },
    { id: 6, dificuldade: 'facil', pergunta: 'Qual é a cor da cruz central do escudo do Vasco?', hex: '#000000' },
    { id: 7, dificuldade: 'facil', pergunta: 'Qual é a cor da estrela no centro do escudo do Botafogo?', hex: '#000000' },
    { id: 8, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da faixa central do escudo do Fluminense?', hex: '#7A1730' },
    { id: 9, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do círculo externo do escudo do Grêmio?', hex: '#0B3D91' },
    { id: 10, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do círculo externo do escudo do Internacional?', hex: '#D71920' },
    { id: 11, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do círculo externo do escudo do Cruzeiro?', hex: '#005CA9' },
    { id: 12, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do fundo do escudo do Atlético Mineiro?', hex: '#000000' },
    { id: 13, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do círculo externo do escudo do Bahia?', hex: '#005CA9' },
    { id: 14, dificuldade: 'facil', pergunta: 'Qual é a cor predominante das faixas verticais do escudo do Sport?', hex: '#D71920' },
    { id: 15, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da parte central do escudo do Fortaleza?', hex: '#D71920' },
    { id: 16, dificuldade: 'facil', pergunta: 'Qual é a cor predominante das faixas do escudo do Ceará?', hex: '#000000' },
    { id: 17, dificuldade: 'facil', pergunta: 'Qual é a cor predominante das faixas diagonais do escudo do Athletico?', hex: '#D71920' },
    { id: 18, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do círculo externo do escudo do Coritiba?', hex: '#006B3F' },
    { id: 19, dificuldade: 'facil', pergunta: 'Qual é a cor predominante das listras do escudo do Vitória?', hex: '#D71920' },
    { id: 20, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do fundo do escudo do Bragantino?', hex: '#D71920' },
    { id: 21, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do círculo central do escudo da Seleção Brasileira?', hex: '#F6C800' },
    { id: 22, dificuldade: 'facil', pergunta: 'Qual é a cor predominante das faixas verticais do escudo da Argentina?', hex: '#75AADB' },
    { id: 23, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da águia no escudo da Alemanha?', hex: '#000000' },
    { id: 24, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do galo no escudo da França?', hex: '#0055A4' },
    { id: 25, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da cruz no centro do escudo de Portugal?', hex: '#D71920' },
    { id: 26, dificuldade: 'media', pergunta: 'Qual é a cor predominante das letras CRF no centro do escudo do Flamengo?', hex: '#000000' },
    { id: 27, dificuldade: 'media', pergunta: 'Qual é a cor predominante do barco representado no escudo do Corinthians?', hex: '#000000' },
    { id: 28, dificuldade: 'media', pergunta: 'Qual é a cor predominante da letra no centro do escudo do Palmeiras?', hex: '#FFFFFF' },
    { id: 29, dificuldade: 'media', pergunta: 'Qual é a cor predominante da parte superior do escudo do São Paulo?', hex: '#000000' },
    { id: 30, dificuldade: 'media', pergunta: 'Qual é a cor predominante da bola representada no escudo do Santos?', hex: '#000000' },
    { id: 31, dificuldade: 'media', pergunta: 'Qual é a cor predominante da caravela representada no escudo do Vasco?', hex: '#000000' },
    { id: 32, dificuldade: 'media', pergunta: 'Qual é a cor predominante das letras do escudo do Fluminense?', hex: '#FFFFFF' },
    { id: 33, dificuldade: 'media', pergunta: 'Qual é a cor predominante da faixa central do escudo do Grêmio?', hex: '#000000' },
    { id: 34, dificuldade: 'media', pergunta: 'Qual é a cor predominante das letras no centro do escudo do Internacional?', hex: '#FFFFFF' },
    { id: 35, dificuldade: 'media', pergunta: 'Qual é a cor predominante das estrelas no centro do escudo do Cruzeiro?', hex: '#FFFFFF' },
    { id: 36, dificuldade: 'media', pergunta: 'Qual é a cor predominante da estrela acima do escudo do Atlético Mineiro?', hex: '#F6C800' },
    { id: 37, dificuldade: 'media', pergunta: 'Qual é a cor predominante da faixa diagonal no escudo do Bahia?', hex: '#D71920' },
    { id: 38, dificuldade: 'media', pergunta: 'Qual é a cor predominante das listras verticais do escudo do Fortaleza?', hex: '#0055A4' },
    { id: 39, dificuldade: 'media', pergunta: 'Qual é a cor predominante da borda do escudo do Botafogo?', hex: '#000000' },
    { id: 40, dificuldade: 'media', pergunta: 'Qual é a cor predominante da faixa que atravessa o escudo da Seleção Brasileira?', hex: '#FFFFFF' },
    { id: 41, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do detalhe central acima das faixas no escudo da Argentina?', hex: '#F6C800' },
    { id: 42, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da coroa no escudo da Espanha?', hex: '#F6C800' },
    { id: 43, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante das três coroas no escudo da Inglaterra?', hex: '#D71920' },
    { id: 44, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da faixa central da bandeira no escudo da Itália?', hex: '#FFFFFF' },
    { id: 45, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do sol no escudo do Uruguai?', hex: '#F6C800' },
    { id: 46, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da águia no escudo do México?', hex: '#5B3924' },
    { id: 47, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do símbolo central no escudo da Seleção Japonesa?', hex: '#D71920' },
    { id: 48, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do padrão de quadrados no escudo da Croácia?', hex: '#D71920' },
    { id: 49, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da estrela no centro do escudo do Marrocos?', hex: '#D71920' },
    { id: 50, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do leão no escudo da Seleção Holandesa?', hex: '#F28C28' },
  ],
  cartoon: [
    { id: 1, dificuldade: 'facil', pergunta: 'Qual é a cor do vestido da Florzinha?', hex: '#E94B5F' },
    { id: 2, dificuldade: 'facil', pergunta: 'Qual é a cor do vestido da Lindinha?', hex: '#5DADE2' },
    { id: 3, dificuldade: 'facil', pergunta: 'Qual é a cor do vestido da Docinho?', hex: '#55B947' },
    { id: 4, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo da Florzinha?', hex: '#E84A35' },
    { id: 5, dificuldade: 'facil', pergunta: 'Qual é a cor do pelo do Macaco Louco?', hex: '#704B91' },
    { id: 6, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo de Dexter?', hex: '#E46B2E' },
    { id: 7, dificuldade: 'facil', pergunta: 'Qual é a cor da armação dos óculos de Dexter?', hex: '#4A3026' },
    { id: 8, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo de Dee Dee?', hex: '#E9B4D0' },
    { id: 9, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo de Coragem?', hex: '#C98AA5' },
    { id: 10, dificuldade: 'facil', pergunta: 'Qual é a cor do suéter de Muriel?', hex: '#F2B84B' },
    { id: 11, dificuldade: 'facil', pergunta: 'Qual é a cor da camisa de Edd?', hex: '#3D9B72' },
    { id: 12, dificuldade: 'facil', pergunta: 'Qual é a cor da camisa de Eddy?', hex: '#E6B83F' },
    { id: 13, dificuldade: 'facil', pergunta: 'Qual é a cor da camisa de Ed?', hex: '#7C3F91' },
    { id: 14, dificuldade: 'facil', pergunta: 'Qual é a cor do vestido de Mandy?', hex: '#E8A6B9' },
    { id: 15, dificuldade: 'facil', pergunta: 'Qual é a cor da camisa de Billy?', hex: '#F2C84B' },
    { id: 16, dificuldade: 'facil', pergunta: 'Qual é a cor da gravata de Billy?', hex: '#7A3E91' },
    { id: 17, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo de Johnny Bravo?', hex: '#E2A52F' },
    { id: 18, dificuldade: 'facil', pergunta: 'Qual é a cor da camisa de Johnny Bravo?', hex: '#1D6FA5' },
    { id: 19, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da pele de Quatro Braços?', hex: '#B83B32' },
    { id: 20, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de XLR8?', hex: '#202B35' },
    { id: 21, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Diamante?', hex: '#49B8C9' },
    { id: 22, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Chama?', hex: '#E35A2B' },
    { id: 23, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Massa Cinzenta?', hex: '#8A9A9B' },
    { id: 24, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Besta?', hex: '#B8A33A' },
    { id: 25, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Ultra T?', hex: '#252525' },
    { id: 26, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Cipó Selvagem?', hex: '#4B9B45' },
    { id: 27, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Fantasmático?', hex: '#A9D6C2' },
    { id: 28, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Mordecai?', hex: '#4A8DB8' },
    { id: 29, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Rigby?', hex: '#A86F3D' },
    { id: 30, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Musculoso?', hex: '#3E8B47' },
    { id: 31, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Jake?', hex: '#F2C84B' },
    { id: 32, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da camisa de Finn?', hex: '#5A91C9' },
    { id: 33, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do cabelo da Princesa Jujuba?', hex: '#E8A2C1' },
    { id: 34, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo do Rei Gelado?', hex: '#5E82C1' },
    { id: 35, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Gumball?', hex: '#5DA9D6' },
    { id: 36, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Darwin?', hex: '#F29C38' },
    { id: 37, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Anais?', hex: '#E88FA8' },
    { id: 38, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do traje de Robin?', hex: '#273C72' },
    { id: 39, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da pele de Ravena?', hex: '#6F5AA8' },
    { id: 40, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da pele de Estelar?', hex: '#A85CB5' },
    { id: 41, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da pele de Mutano?', hex: '#4DAF55' },
    { id: 42, dificuldade: 'facil', pergunta: 'Qual é a cor predominante das partes metálicas de Cyborg?', hex: '#8D949A' },
    { id: 43, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da camisa de Steven?', hex: '#E84C3D' },
    { id: 44, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do cabelo de Steven?', hex: '#4A2B26' },
    { id: 45, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa do Irmão do Jorel?', hex: '#E8A52B' },
    { id: 46, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do vestido da Lara?', hex: '#E6A5C0' },
    { id: 47, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Rex?', hex: '#273B63' },
    { id: 48, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Pops?', hex: '#F0B87A' },
    { id: 49, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Marceline?', hex: '#3A303F' },
    { id: 50, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Insectóide?', hex: '#6E7A35' },
    { id: 51, dificuldade: 'media', pergunta: 'Qual é a cor predominante da gravata do Professor Utônio?', hex: '#D83A3A' },
    { id: 52, dificuldade: 'media', pergunta: 'Qual é a cor predominante do vestido da Princesa Maisgrana?', hex: '#E8B23A' },
    { id: 53, dificuldade: 'media', pergunta: 'Qual é a cor predominante do vestido de Dee Dee?', hex: '#E8A0C0' },
    { id: 54, dificuldade: 'media', pergunta: 'Qual é a cor predominante do vestido de Muriel?', hex: '#D88A48' },
    { id: 55, dificuldade: 'media', pergunta: 'Qual é a cor predominante do boné de Eddy?', hex: '#D9A92E' },
    { id: 56, dificuldade: 'media', pergunta: 'Qual é a cor predominante da túnica de Puro Osso?', hex: '#5D2F68' },
    { id: 57, dificuldade: 'media', pergunta: 'Qual é a cor predominante dos óculos de Johnny Bravo?', hex: '#252525' },
    { id: 58, dificuldade: 'media', pergunta: 'Qual é a cor predominante do cinto de Quatro Braços?', hex: '#27313A' },
    { id: 59, dificuldade: 'media', pergunta: 'Qual é a cor predominante das marcas no capacete de XLR8?', hex: '#F0B52B' },
    { id: 60, dificuldade: 'media', pergunta: 'Qual é a cor predominante dos cristais do corpo de Diamante?', hex: '#72D3DE' },
    { id: 61, dificuldade: 'media', pergunta: 'Qual é a cor predominante das chamas produzidas por Chama?', hex: '#F6A623' },
    { id: 62, dificuldade: 'media', pergunta: 'Qual é a cor predominante das linhas luminosas do corpo de Ultra T?', hex: '#6FCB3A' },
    { id: 63, dificuldade: 'media', pergunta: 'Qual é a cor predominante das plantas que formam o corpo de Cipó Selvagem?', hex: '#4B9B45' },
    { id: 64, dificuldade: 'media', pergunta: 'Qual é a cor predominante do corpo de Pairulito?', hex: '#5B8CC5' },
    { id: 65, dificuldade: 'media', pergunta: 'Qual é a cor predominante do corpo de Benson?', hex: '#C94B55' },
    { id: 66, dificuldade: 'media', pergunta: 'Qual é a cor predominante da pele da Princesa Caroço?', hex: '#B86AA7' },
    { id: 67, dificuldade: 'media', pergunta: 'Qual é a cor predominante da guitarra de Marceline?', hex: '#9B2431' },
    { id: 68, dificuldade: 'media', pergunta: 'Qual é a cor predominante do corpo de Nicole?', hex: '#5D83B3' },
    { id: 69, dificuldade: 'media', pergunta: 'Qual é a cor predominante do corpo de Tobias?', hex: '#F0B34A' },
    { id: 70, dificuldade: 'media', pergunta: 'Qual é a cor predominante da capa de Ravena?', hex: '#40306A' },
    { id: 71, dificuldade: 'media', pergunta: 'Qual é a cor predominante do cabelo de Estelar?', hex: '#D84A35' },
    { id: 72, dificuldade: 'media', pergunta: 'Qual é a cor predominante das partes mecânicas do corpo de Cyborg?', hex: '#4B5158' },
    { id: 73, dificuldade: 'media', pergunta: 'Qual é a cor predominante da roupa de Lara?', hex: '#E6A5C0' },
    { id: 74, dificuldade: 'media', pergunta: 'Qual é a cor predominante do cabelo de Garnet?', hex: '#382C48' },
    { id: 75, dificuldade: 'media', pergunta: 'Qual é a cor predominante do cabelo de Pérola?', hex: '#F2B5C4' },
    { id: 76, dificuldade: 'media', pergunta: 'Qual é a cor predominante do cabelo de Ametista?', hex: '#8B4D9B' },
    { id: 77, dificuldade: 'media', pergunta: 'Qual é a cor predominante das partes mecânicas de Rex?', hex: '#87929B' },
    { id: 78, dificuldade: 'media', pergunta: 'Qual é a cor predominante dos olhos de Besta?', hex: '#E5A92F' },
    { id: 79, dificuldade: 'media', pergunta: 'Qual é a cor predominante do símbolo do Omnitrix em Fantasmático?', hex: '#8BCBBA' },
    { id: 80, dificuldade: 'media', pergunta: 'Qual é a cor predominante dos olhos de Insectóide?', hex: '#D8D04A' },
    { id: 81, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do pelo do Macaco Louco em sua forma original?', hex: '#704B91' },
    { id: 82, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do laço de Dee Dee?', hex: '#E77AAE' },
    { id: 83, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do chapéu de Eustácio?', hex: '#B86F3D' },
    { id: 84, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da foice de Puro Osso?', hex: '#70777D' },
    { id: 85, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante das faixas no corpo de Quatro Braços?', hex: '#D6A12F' },
    { id: 86, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da viseira de XLR8?', hex: '#D9B83E' },
    { id: 87, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante dos detalhes do uniforme de Diamante?', hex: '#294C68' },
    { id: 88, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante das pedras que aparecem na cabeça de Chama?', hex: '#5B3028' },
    { id: 89, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante das linhas que percorrem o corpo de Ultra T?', hex: '#6FCB3A' },
    { id: 90, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante das asas de Pairulito?', hex: '#6AA5D8' },
    { id: 91, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da guitarra de Marceline?', hex: '#9B2431' },
    { id: 92, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante dos olhos de Gumball?', hex: '#65B8D4' },
    { id: 93, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante dos olhos de Ravena?', hex: '#4A2E67' },
    { id: 94, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da roupa de Pérola?', hex: '#B8D7D2' },
    { id: 95, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da roupa de Garnet?', hex: '#4C315B' },
    { id: 96, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da roupa de Ametista?', hex: '#6C3E7B' },
    { id: 97, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da energia produzida pelas máquinas de Rex?', hex: '#4DB6C7' },
    { id: 98, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante das sementes explosivas de Cipó Selvagem?', hex: '#C7A52A' },
    { id: 99, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante dos detalhes do corpo de Fantasmático?', hex: '#6D8F82' },
    { id: 100, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante das asas de Insectóide?', hex: '#6E7A35' },
  ],
  nickelodeon: [
    { id: 1, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo de Bob Esponja?', hex: '#F2D52E' },
    { id: 2, dificuldade: 'facil', pergunta: 'Qual é a cor da gravata de Bob Esponja?', hex: '#C62828' },
    { id: 3, dificuldade: 'facil', pergunta: 'Qual é a cor da calça de Bob Esponja?', hex: '#8A6339' },
    { id: 4, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo de Patrick?', hex: '#F28CA8' },
    { id: 5, dificuldade: 'facil', pergunta: 'Qual é a cor da bermuda de Patrick?', hex: '#72A95A' },
    { id: 6, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo de Lula Molusco?', hex: '#8BB5A5' },
    { id: 7, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo de Sandy?', hex: '#B88652' },
    { id: 8, dificuldade: 'facil', pergunta: 'Qual é a cor do uniforme de Sandy?', hex: '#6B9EBD' },
    { id: 9, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Gary?', hex: '#91A9B7' },
    { id: 10, dificuldade: 'facil', pergunta: 'Qual é a cor da casca de Plankton?', hex: '#2F9E44' },
    { id: 11, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo de Timmy?', hex: '#7A4A2B' },
    { id: 12, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo de Cosmo?', hex: '#6BCB5E' },
    { id: 13, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo de Wanda?', hex: '#F08AA4' },
    { id: 14, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo de Wanda?', hex: '#8E62B5' },
    { id: 15, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Timmy?', hex: '#8A55A6' },
    { id: 16, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Vicky?', hex: '#E64A35' },
    { id: 17, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo de Jimmy?', hex: '#7A4A2B' },
    { id: 18, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da camisa de Jimmy?', hex: '#D94B3D' },
    { id: 19, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Carl?', hex: '#6DA7C8' },
    { id: 20, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Sheen?', hex: '#4A9B55' },
    { id: 21, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo de Cindy?', hex: '#F0D2A2' },
    { id: 22, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Cindy?', hex: '#8B5AA8' },
    { id: 23, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Aang?', hex: '#D8A33A' },
    { id: 24, dificuldade: 'facil', pergunta: 'Qual é a cor das tatuagens de Aang?', hex: '#5C86B2' },
    { id: 25, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Katara?', hex: '#3C75A8' },
    { id: 26, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Sokka?', hex: '#536E8A' },
    { id: 27, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Zuko?', hex: '#9B382C' },
    { id: 28, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo de Azula?', hex: '#171717' },
    { id: 29, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Toph?', hex: '#8A6A45' },
    { id: 30, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do pelo de Appa?', hex: '#B58A55' },
    { id: 31, dificuldade: 'facil', pergunta: 'Qual é a cor da máscara de Leonardo?', hex: '#2474C6' },
    { id: 32, dificuldade: 'facil', pergunta: 'Qual é a cor da máscara de Raphael?', hex: '#D52B32' },
    { id: 33, dificuldade: 'facil', pergunta: 'Qual é a cor da máscara de Donatello?', hex: '#7447A8' },
    { id: 34, dificuldade: 'facil', pergunta: 'Qual é a cor da máscara de Michelangelo?', hex: '#E89A2F' },
    { id: 35, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo das Tartarugas Ninja?', hex: '#4C9B54' },
    { id: 36, dificuldade: 'facil', pergunta: "Qual é a cor predominante da roupa de April O'Neil?", hex: '#E4C12E' },
    { id: 37, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do pelo de Po?', hex: '#252525' },
    { id: 38, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Po?', hex: '#7A9B49' },
    { id: 39, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do pelo de Tigresa?', hex: '#D8A338' },
    { id: 40, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Mestre Shifu?', hex: '#A34B3B' },
    { id: 41, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Kowalski?', hex: '#30353A' },
    { id: 42, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do bico de Rico?', hex: '#E3A72F' },
    { id: 43, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Rei Julien?', hex: '#A7A88B' },
    { id: 44, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da cauda de Rei Julien?', hex: '#D5A84A' },
    { id: 45, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de B.O.B.?', hex: '#74A9C4' },
    { id: 46, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Susan?', hex: '#79A5D1' },
    { id: 47, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Dr. Barata?', hex: '#65743E' },
    { id: 48, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da camisa de Phineas?', hex: '#E85A35' },
    { id: 49, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Ferb?', hex: '#6D8B55' },
    { id: 50, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo de Perry?', hex: '#6E9A48' },
    { id: 51, dificuldade: 'media', pergunta: 'Qual é a cor da gravata de Patrick?', hex: '#C94A3A' },
    { id: 52, dificuldade: 'media', pergunta: 'Qual é a cor predominante do uniforme do Sr. Siriguejo?', hex: '#2F7A4A' },
    { id: 53, dificuldade: 'media', pergunta: 'Qual é a cor predominante da roupa de Cosmo?', hex: '#BBD5E5' },
    { id: 54, dificuldade: 'media', pergunta: 'Qual é a cor predominante da roupa de Wanda?', hex: '#E5B6C9' },
    { id: 55, dificuldade: 'media', pergunta: 'Qual é a cor predominante dos óculos de Carl?', hex: '#6B4A35' },
    { id: 56, dificuldade: 'media', pergunta: 'Qual é a cor predominante da roupa de Libby?', hex: '#D64E5A' },
    { id: 57, dificuldade: 'media', pergunta: 'Qual é a cor predominante da roupa de Iroh?', hex: '#B84B32' },
    { id: 58, dificuldade: 'media', pergunta: 'Qual é a cor predominante do traje de combate de Suki?', hex: '#5B7D50' },
    { id: 59, dificuldade: 'media', pergunta: 'Qual é a cor predominante da roupa de Mai?', hex: '#3A3A4B' },
    { id: 60, dificuldade: 'media', pergunta: 'Qual é a cor predominante da roupa de Ty Lee?', hex: '#D85B4A' },
    { id: 61, dificuldade: 'media', pergunta: 'Qual é a cor predominante do bastão de Donatello?', hex: '#8A5B35' },
    { id: 62, dificuldade: 'media', pergunta: 'Qual é a cor predominante das espadas de Leonardo?', hex: '#7B858A' },
    { id: 63, dificuldade: 'media', pergunta: 'Qual é a cor predominante das armas de Michelangelo?', hex: '#9B6A42' },
    { id: 64, dificuldade: 'media', pergunta: 'Qual é a cor predominante do bastão de Mestre Shifu?', hex: '#8A5A35' },
    { id: 65, dificuldade: 'media', pergunta: 'Qual é a cor predominante da roupa de Mestre Oogway?', hex: '#6B8A43' },
    { id: 66, dificuldade: 'media', pergunta: 'Qual é a cor predominante do corpo de Skipper?', hex: '#34393D' },
    { id: 67, dificuldade: 'media', pergunta: 'Qual é a cor predominante do corpo de Private?', hex: '#555B5F' },
    { id: 68, dificuldade: 'media', pergunta: 'Qual é a cor predominante do traje de Gallaxhar?', hex: '#5B397A' },
    { id: 69, dificuldade: 'media', pergunta: 'Qual é a cor predominante do vestido de Susan?', hex: '#6B82C1' },
    { id: 70, dificuldade: 'media', pergunta: 'Qual é a cor predominante da roupa de Candace?', hex: '#D94B4B' },
    { id: 71, dificuldade: 'media', pergunta: 'Qual é a cor predominante da roupa de Isabella?', hex: '#E7A52F' },
    { id: 72, dificuldade: 'media', pergunta: 'Qual é a cor predominante da roupa de Buford?', hex: '#6A82A5' },
    { id: 73, dificuldade: 'media', pergunta: 'Qual é a cor predominante da roupa de Baljeet?', hex: '#4C8C63' },
    { id: 74, dificuldade: 'media', pergunta: 'Qual é a cor predominante do chapéu de Perry?', hex: '#A87B35' },
    { id: 75, dificuldade: 'media', pergunta: 'Qual é a cor predominante da roupa do Dr. Doofenshmirtz?', hex: '#7866A8' },
    { id: 76, dificuldade: 'media', pergunta: 'Qual é a cor predominante da casa de Patrick?', hex: '#E58B9D' },
    { id: 77, dificuldade: 'media', pergunta: 'Qual é a cor predominante da roupa de Chester?', hex: '#4A78B2' },
    { id: 78, dificuldade: 'media', pergunta: 'Qual é a cor predominante da roupa de Goddard?', hex: '#4A83B7' },
    { id: 79, dificuldade: 'media', pergunta: 'Qual é a cor predominante do traje de Destruidor?', hex: '#555B65' },
    { id: 80, dificuldade: 'media', pergunta: 'Qual é a cor predominante do pelo de Tai Lung?', hex: '#A8A4A1' },
    { id: 81, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da gravata usada pelo Sr. Siriguejo?', hex: '#6B3D91' },
    { id: 82, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da casa de Lula Molusco?', hex: '#A86C8D' },
    { id: 83, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da coroa de Rei Vicky?', hex: '#E2B536' },
    { id: 84, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do cabelo de Hugh Neutron?', hex: '#A8733D' },
    { id: 85, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da roupa de Avatar Roku?', hex: '#A84C35' },
    { id: 86, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante das roupas de Mestre Pakku?', hex: '#476E98' },
    { id: 87, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da faixa usada por Splinter?', hex: '#9B6A3E' },
    { id: 88, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da armadura usada por Lord Shen?', hex: '#8D8C91' },
    { id: 89, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da coroa usada por Rei Julien?', hex: '#D4A52E' },
    { id: 90, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do uniforme usado pelo General W.R. Monger?', hex: '#4A5663' },
    { id: 91, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do vestido usado por Linda Flynn-Fletcher?', hex: '#D96C3B' },
    { id: 92, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do uniforme de Major Monogram?', hex: '#4E6B52' },
    { id: 93, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da roupa de Jeremy?', hex: '#5D79A4' },
    { id: 94, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do chapéu usado por Ferb?', hex: '#D5A83A' },
    { id: 95, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do pelo de Perry quando ele está caracterizado como agente?', hex: '#5B8F45' },
    { id: 96, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do traje de combate de Zuko?', hex: '#25252B' },
    { id: 97, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do traje usado por Casey Jones?', hex: '#66727A' },
    { id: 98, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da roupa de Mestre Croc?', hex: '#5B7D62' },
    { id: 99, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do pelo de Mort?', hex: '#B9A98A' },
    { id: 100, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do corpo de The Missing Link?', hex: '#4E9A96' },
  ],
};
