// Curated "Frase da IA" question bank: each question's hex IS the round's
// secret color (converted to HSL), so the AI phrase and the color to guess
// are actually linked — unlike the old generic AI_PHRASE_BANK fallback.
// Keyed by LOBBY_THEMES id (shared/gameData.ts).

export type AiDifficulty = 'facil' | 'media' | 'dificil';

export interface AiQuestion {
  id: number;
  dificuldade: AiDifficulty;
  pergunta: string;
  hex: string;
}

export const AI_QUESTIONS: Record<string, AiQuestion[]> = {
  clash: [
    { id: 1, dificuldade: 'facil', pergunta: 'Qual é a cor da armadura dourada do Príncipe?', hex: '#D9A62E' },
    { id: 2, dificuldade: 'facil', pergunta: 'Qual é a cor do cavalo do Príncipe?', hex: '#8A542E' },
    { id: 3, dificuldade: 'facil', pergunta: 'Qual é a cor da barba do Lenhador?', hex: '#6B3E22' },
    { id: 4, dificuldade: 'facil', pergunta: 'Qual é a cor da Fúria?', hex: '#A855F7' },
    { id: 5, dificuldade: 'facil', pergunta: 'Qual é a cor principal do cabelo do Mago?', hex: '#6B3FA0' },
    { id: 6, dificuldade: 'facil', pergunta: 'Qual é a cor das chamas da Bola de Fogo?', hex: '#FF6A00' },
    { id: 7, dificuldade: 'facil', pergunta: 'Qual é a cor do gelo do Feitiço de Gelo?', hex: '#8DEBFF' },
    { id: 8, dificuldade: 'facil', pergunta: 'Qual é a cor dos cabelos da Valquíria?', hex: '#E85D3F' },
    { id: 9, dificuldade: 'facil', pergunta: 'Qual é a cor da armadura do Cavaleiro?', hex: '#6E737A' },
    { id: 10, dificuldade: 'facil', pergunta: 'Qual é a cor do escudo do Príncipe das Trevas?', hex: '#252833' },
    { id: 11, dificuldade: 'facil', pergunta: 'Qual é a cor da pele dos Goblins?', hex: '#63B52D' },
    { id: 12, dificuldade: 'facil', pergunta: 'Qual é a cor da pele dos Goblins Lanceiros?', hex: '#6FBE35' },
    { id: 13, dificuldade: 'facil', pergunta: 'Qual é a cor da roupa do Goblin?', hex: '#4C8F26' },
    { id: 14, dificuldade: 'facil', pergunta: 'Qual é a cor do capacete do Mini P.E.K.K.A?', hex: '#5E6470' },
    { id: 15, dificuldade: 'facil', pergunta: 'Qual é a cor dos olhos do Mini P.E.K.K.A?', hex: '#35C8FF' },
    { id: 16, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo da Mosqueteira?', hex: '#6B3E24' },
    { id: 17, dificuldade: 'facil', pergunta: 'Qual é a cor do vestido da Mosqueteira?', hex: '#3D6FA8' },
    { id: 18, dificuldade: 'facil', pergunta: 'Qual é a cor da roupa da Princesa?', hex: '#E85C73' },
    { id: 19, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo da Princesa?', hex: '#8A4B2B' },
    { id: 20, dificuldade: 'facil', pergunta: 'Qual é a cor do fogo do Dragão Bebê?', hex: '#FF7A00' },
    { id: 21, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo do Dragão Bebê?', hex: '#75B82C' },
    { id: 22, dificuldade: 'facil', pergunta: 'Qual é a cor da capa do Mago de Gelo?', hex: '#3E7DB8' },
    { id: 23, dificuldade: 'facil', pergunta: 'Qual é a cor da pele do Esqueleto?', hex: '#E8E4D8' },
    { id: 24, dificuldade: 'facil', pergunta: 'Qual é a cor do fogo do Espírito de Fogo?', hex: '#FF8A00' },
    { id: 25, dificuldade: 'facil', pergunta: 'Qual é a cor do Espírito de Gelo?', hex: '#74DFFF' },
    { id: 26, dificuldade: 'facil', pergunta: 'Qual é a cor do Espírito Elétrico?', hex: '#4FCBFF' },
    { id: 27, dificuldade: 'facil', pergunta: 'Qual é a cor do raio do Espírito Elétrico?', hex: '#8BE9FF' },
    { id: 28, dificuldade: 'facil', pergunta: 'Qual é a cor da roupa do Lenhador?', hex: '#A52E2E' },
    { id: 29, dificuldade: 'facil', pergunta: 'Qual é a cor da barba do Gigante?', hex: '#C17A42' },
    { id: 30, dificuldade: 'facil', pergunta: 'Qual é a cor da pele do Gigante?', hex: '#E5A36D' },
    { id: 31, dificuldade: 'facil', pergunta: 'Qual é a cor da roupa do Príncipe das Trevas?', hex: '#242631' },
    { id: 32, dificuldade: 'facil', pergunta: 'Qual é a cor da capa da Bruxa?', hex: '#6A3D8F' },
    { id: 33, dificuldade: 'facil', pergunta: 'Qual é a cor dos olhos da Bruxa?', hex: '#D84AFF' },
    { id: 34, dificuldade: 'facil', pergunta: 'Qual é a cor dos cabelos da Bruxa?', hex: '#29202F' },
    { id: 35, dificuldade: 'facil', pergunta: 'Qual é a cor da roupa do Mago Elétrico?', hex: '#234A91' },
    { id: 36, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo do Mago Elétrico?', hex: '#E6D9C3' },
    { id: 37, dificuldade: 'facil', pergunta: 'Qual é a cor do raio do Mago Elétrico?', hex: '#6DDCFF' },
    { id: 38, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo do Balão?', hex: '#A83232' },
    { id: 39, dificuldade: 'facil', pergunta: 'Qual é a cor da cesta do Balão?', hex: '#9A632E' },
    { id: 40, dificuldade: 'facil', pergunta: 'Qual é a cor do fogo da Torre Inferno?', hex: '#FF5A00' },
    { id: 41, dificuldade: 'facil', pergunta: 'Qual é a cor principal do Dragão Infernal?', hex: '#4D2923' },
    { id: 42, dificuldade: 'facil', pergunta: 'Qual é a cor do fogo do Dragão Infernal?', hex: '#FF5B16' },
    { id: 43, dificuldade: 'facil', pergunta: 'Qual é a cor da armadura do Mega Cavaleiro?', hex: '#292D3A' },
    { id: 44, dificuldade: 'facil', pergunta: 'Qual é a cor dos olhos do Mega Cavaleiro?', hex: '#FF5A3D' },
    { id: 45, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo do Rei?', hex: '#7A4A2B' },
    { id: 46, dificuldade: 'facil', pergunta: 'Qual é a cor da coroa do Rei?', hex: '#F5C542' },
    { id: 47, dificuldade: 'facil', pergunta: 'Qual é a cor da camisa do Rei?', hex: '#3E75B6' },
    { id: 48, dificuldade: 'facil', pergunta: 'Qual é a cor do elixir?', hex: '#D946EF' },
    { id: 49, dificuldade: 'facil', pergunta: 'Qual é a cor da água do rio da Arena?', hex: '#3DB7D9' },
    { id: 50, dificuldade: 'facil', pergunta: 'Qual é a cor das Torres da Coroa?', hex: '#D8A23A' },
    { id: 51, dificuldade: 'media', pergunta: 'Qual é a cor da ponta da lança do Príncipe?', hex: '#DCE8F2' },
    { id: 52, dificuldade: 'media', pergunta: 'Qual é a cor da faixa azul do Príncipe?', hex: '#3975C6' },
    { id: 53, dificuldade: 'media', pergunta: 'Qual é a cor do pelo mais claro do cavalo do Príncipe?', hex: '#A96B3B' },
    { id: 54, dificuldade: 'media', pergunta: 'Qual é a cor do machado do Lenhador?', hex: '#8C9198' },
    { id: 55, dificuldade: 'media', pergunta: 'Qual é a cor da camisa do Lenhador?', hex: '#B83B3B' },
    { id: 56, dificuldade: 'media', pergunta: 'Qual é a cor do frasco de Fúria?', hex: '#7D3DB8' },
    { id: 57, dificuldade: 'media', pergunta: 'Qual é a cor do brilho ao redor da Fúria?', hex: '#D66CFF' },
    { id: 58, dificuldade: 'media', pergunta: 'Qual é a cor central da Bola de Fogo?', hex: '#FFD23F' },
    { id: 59, dificuldade: 'media', pergunta: 'Qual é a cor da borda das chamas da Bola de Fogo?', hex: '#E83B00' },
    { id: 60, dificuldade: 'media', pergunta: 'Qual é a cor da fumaça deixada pelo Feitiço de Gelo?', hex: '#C8F6FF' },
    { id: 61, dificuldade: 'media', pergunta: 'Qual é a cor da máscara do Príncipe das Trevas?', hex: '#161820' },
    { id: 62, dificuldade: 'media', pergunta: 'Qual é a cor do detalhe dourado do escudo do Príncipe das Trevas?', hex: '#C99A32' },
    { id: 63, dificuldade: 'media', pergunta: 'Qual é a cor do cabelo da Arqueira?', hex: '#8A542D' },
    { id: 64, dificuldade: 'media', pergunta: 'Qual é a cor da roupa da Arqueira?', hex: '#D95A8A' },
    { id: 65, dificuldade: 'media', pergunta: 'Qual é a cor das flechas das Arqueiras?', hex: '#C49A5A' },
    { id: 66, dificuldade: 'media', pergunta: 'Qual é a cor da armadura do P.E.K.K.A?', hex: '#303746' },
    { id: 67, dificuldade: 'media', pergunta: 'Qual é a cor dos olhos do P.E.K.K.A?', hex: '#C93AFF' },
    { id: 68, dificuldade: 'media', pergunta: 'Qual é a cor do fogo nos olhos do P.E.K.K.A?', hex: '#8B2CFF' },
    { id: 69, dificuldade: 'media', pergunta: 'Qual é a cor da roupa da Bandida?', hex: '#5A4B70' },
    { id: 70, dificuldade: 'media', pergunta: 'Qual é a cor da máscara da Bandida?', hex: '#2B2634' },
    { id: 71, dificuldade: 'media', pergunta: 'Qual é a cor do efeito do dash da Bandida?', hex: '#B8A5FF' },
    { id: 72, dificuldade: 'media', pergunta: 'Qual é a cor do cabelo do Cavaleiro Dourado?', hex: '#C98B3A' },
    { id: 73, dificuldade: 'media', pergunta: 'Qual é a cor da armadura do Cavaleiro Dourado?', hex: '#E3B84A' },
    { id: 74, dificuldade: 'media', pergunta: 'Qual é a cor do brilho da habilidade do Cavaleiro Dourado?', hex: '#FFD75A' },
    { id: 75, dificuldade: 'media', pergunta: 'Qual é a cor da capa do Mago?', hex: '#7436A5' },
    { id: 76, dificuldade: 'media', pergunta: 'Qual é a cor do cinto do Mago?', hex: '#E6A72F' },
    { id: 77, dificuldade: 'media', pergunta: 'Qual é a cor das faíscas do Mago Elétrico?', hex: '#69D9FF' },
    { id: 78, dificuldade: 'media', pergunta: 'Qual é a cor do raio do Dragão Infernal quando está carregando?', hex: '#FF9D24' },
    { id: 79, dificuldade: 'media', pergunta: 'Qual é a cor do brilho mais intenso no centro do raio do Dragão Infernal?', hex: '#FFE15C' },
    { id: 80, dificuldade: 'media', pergunta: 'Qual é a cor do fogo da Torre Inferno quando está totalmente carregada?', hex: '#FF2D00' },
    { id: 81, dificuldade: 'dificil', pergunta: 'Qual é a cor do centro do raio do Dragão Infernal no estágio máximo?', hex: '#FFF19A' },
    { id: 82, dificuldade: 'dificil', pergunta: 'Qual é a cor da borda externa do raio do Dragão Infernal?', hex: '#FF4A00' },
    { id: 83, dificuldade: 'dificil', pergunta: 'Qual é a cor da chama refletida na armadura do Dragão Infernal?', hex: '#FF7133' },
    { id: 84, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho do ataque carregado da Torre Inferno?', hex: '#FF7B00' },
    { id: 85, dificuldade: 'dificil', pergunta: 'Qual é a cor mais clara no centro da explosão da Bola de Fogo?', hex: '#FFF0A3' },
    { id: 86, dificuldade: 'dificil', pergunta: 'Qual é a cor mais escura da fumaça da Bola de Fogo?', hex: '#7A1D0A' },
    { id: 87, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho no centro do efeito da Fúria?', hex: '#E7A1FF' },
    { id: 88, dificuldade: 'dificil', pergunta: 'Qual é a cor da região mais escura do círculo da Fúria?', hex: '#632080' },
    { id: 89, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho do ataque do Mago Elétrico?', hex: '#D8F8FF' },
    { id: 90, dificuldade: 'dificil', pergunta: 'Qual é a cor mais intensa do raio do Mago Elétrico?', hex: '#39C8FF' },
    { id: 91, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho do ataque da Princesa?', hex: '#FFB7C8' },
    { id: 92, dificuldade: 'dificil', pergunta: 'Qual é a cor da chama do Dragão Bebê imediatamente antes da explosão?', hex: '#FFD33D' },
    { id: 93, dificuldade: 'dificil', pergunta: 'Qual é a cor da parte mais escura da armadura do P.E.K.K.A?', hex: '#171A24' },
    { id: 94, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho roxo dos olhos do P.E.K.K.A?', hex: '#B72CFF' },
    { id: 95, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho do ataque do Príncipe quando ele está em carga?', hex: '#D9E8FF' },
    { id: 96, dificuldade: 'dificil', pergunta: 'Qual é a cor do detalhe mais claro da armadura dourada do Príncipe?', hex: '#FFE37A' },
    { id: 97, dificuldade: 'dificil', pergunta: 'Qual é a cor da sombra mais escura da barba do Lenhador?', hex: '#3D2116' },
    { id: 98, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho produzido pelo ataque do Cavaleiro Dourado?', hex: '#FFF0A0' },
    { id: 99, dificuldade: 'dificil', pergunta: 'Qual é a cor da energia do ataque do Espírito Elétrico no momento do impacto?', hex: '#B5F5FF' },
    { id: 100, dificuldade: 'dificil', pergunta: 'Qual é a cor do centro luminoso da explosão do Relâmpago?', hex: '#F4F8FF' },
  ],
};
