// Curated "Frase da IA" question bank: each question's hex IS the round's
// secret color (converted to HSL), so the AI phrase and the color to guess
// are actually linked — unlike the old generic AI_PHRASE_BANK fallback.
// Keyed by LOBBY_THEMES id (shared/gameData.ts).

export type AiDifficulty = 'facil' | 'media' | 'dificil';

export interface AiQuestion {
  id: number;
  dificuldade: AiDifficulty;
  pergunta: string;
  hex: string;
  /** The specific movie/show/team/character the question is about, when the
   *  source data had one (Clash Royale and Marvel's banks didn't). */
  fonte?: string;
}

export const AI_QUESTIONS: Record<string, AiQuestion[]> = {
  clash: [
    { id: 1, dificuldade: 'facil', pergunta: 'Qual é a cor da armadura dourada do Príncipe?', hex: '#D9A62E' },
    { id: 2, dificuldade: 'facil', pergunta: 'Qual é a cor do cavalo do Príncipe?', hex: '#8A542E' },
    { id: 3, dificuldade: 'facil', pergunta: 'Qual é a cor da barba do Lenhador?', hex: '#6B3E22' },
    { id: 4, dificuldade: 'facil', pergunta: 'Qual é a cor da Fúria?', hex: '#A855F7' },
    { id: 5, dificuldade: 'facil', pergunta: 'Qual é a cor principal do cabelo do Mago?', hex: '#6B3FA0' },
    { id: 6, dificuldade: 'facil', pergunta: 'Qual é a cor das chamas da Bola de Fogo?', hex: '#FF6A00' },
    { id: 7, dificuldade: 'facil', pergunta: 'Qual é a cor do gelo do Feitiço de Gelo?', hex: '#8DEBFF' },
    { id: 8, dificuldade: 'facil', pergunta: 'Qual é a cor dos cabelos da Valquíria?', hex: '#E85D3F' },
    { id: 9, dificuldade: 'facil', pergunta: 'Qual é a cor da armadura do Cavaleiro?', hex: '#6E737A' },
    { id: 10, dificuldade: 'facil', pergunta: 'Qual é a cor do escudo do Príncipe das Trevas?', hex: '#252833' },
    { id: 11, dificuldade: 'facil', pergunta: 'Qual é a cor da pele dos Goblins?', hex: '#63B52D' },
    { id: 12, dificuldade: 'facil', pergunta: 'Qual é a cor da pele dos Goblins Lanceiros?', hex: '#6FBE35' },
    { id: 13, dificuldade: 'facil', pergunta: 'Qual é a cor da roupa do Goblin?', hex: '#4C8F26' },
    { id: 14, dificuldade: 'facil', pergunta: 'Qual é a cor do capacete do Mini P.E.K.K.A?', hex: '#5E6470' },
    { id: 15, dificuldade: 'facil', pergunta: 'Qual é a cor dos olhos do Mini P.E.K.K.A?', hex: '#35C8FF' },
    { id: 16, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo da Mosqueteira?', hex: '#6B3E24' },
    { id: 17, dificuldade: 'facil', pergunta: 'Qual é a cor do vestido da Mosqueteira?', hex: '#3D6FA8' },
    { id: 18, dificuldade: 'facil', pergunta: 'Qual é a cor da roupa da Princesa?', hex: '#E85C73' },
    { id: 19, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo da Princesa?', hex: '#8A4B2B' },
    { id: 20, dificuldade: 'facil', pergunta: 'Qual é a cor do fogo do Dragão Bebê?', hex: '#FF7A00' },
    { id: 21, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo do Dragão Bebê?', hex: '#75B82C' },
    { id: 22, dificuldade: 'facil', pergunta: 'Qual é a cor da capa do Mago de Gelo?', hex: '#3E7DB8' },
    { id: 23, dificuldade: 'facil', pergunta: 'Qual é a cor da pele do Esqueleto?', hex: '#E8E4D8' },
    { id: 24, dificuldade: 'facil', pergunta: 'Qual é a cor do fogo do Espírito de Fogo?', hex: '#FF8A00' },
    { id: 25, dificuldade: 'facil', pergunta: 'Qual é a cor do Espírito de Gelo?', hex: '#74DFFF' },
    { id: 26, dificuldade: 'facil', pergunta: 'Qual é a cor do Espírito Elétrico?', hex: '#4FCBFF' },
    { id: 27, dificuldade: 'facil', pergunta: 'Qual é a cor do raio do Espírito Elétrico?', hex: '#8BE9FF' },
    { id: 28, dificuldade: 'facil', pergunta: 'Qual é a cor da roupa do Lenhador?', hex: '#A52E2E' },
    { id: 29, dificuldade: 'facil', pergunta: 'Qual é a cor da barba do Gigante?', hex: '#C17A42' },
    { id: 30, dificuldade: 'facil', pergunta: 'Qual é a cor da pele do Gigante?', hex: '#E5A36D' },
    { id: 31, dificuldade: 'facil', pergunta: 'Qual é a cor da roupa do Príncipe das Trevas?', hex: '#242631' },
    { id: 32, dificuldade: 'facil', pergunta: 'Qual é a cor da capa da Bruxa?', hex: '#6A3D8F' },
    { id: 33, dificuldade: 'facil', pergunta: 'Qual é a cor dos olhos da Bruxa?', hex: '#D84AFF' },
    { id: 34, dificuldade: 'facil', pergunta: 'Qual é a cor dos cabelos da Bruxa?', hex: '#29202F' },
    { id: 35, dificuldade: 'facil', pergunta: 'Qual é a cor da roupa do Mago Elétrico?', hex: '#234A91' },
    { id: 36, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo do Mago Elétrico?', hex: '#E6D9C3' },
    { id: 37, dificuldade: 'facil', pergunta: 'Qual é a cor do raio do Mago Elétrico?', hex: '#6DDCFF' },
    { id: 38, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo do Balão?', hex: '#A83232' },
    { id: 39, dificuldade: 'facil', pergunta: 'Qual é a cor da cesta do Balão?', hex: '#9A632E' },
    { id: 40, dificuldade: 'facil', pergunta: 'Qual é a cor do fogo da Torre Inferno?', hex: '#FF5A00' },
    { id: 41, dificuldade: 'facil', pergunta: 'Qual é a cor principal do Dragão Infernal?', hex: '#4D2923' },
    { id: 42, dificuldade: 'facil', pergunta: 'Qual é a cor do fogo do Dragão Infernal?', hex: '#FF5B16' },
    { id: 43, dificuldade: 'facil', pergunta: 'Qual é a cor da armadura do Mega Cavaleiro?', hex: '#292D3A' },
    { id: 44, dificuldade: 'facil', pergunta: 'Qual é a cor dos olhos do Mega Cavaleiro?', hex: '#FF5A3D' },
    { id: 45, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo do Rei?', hex: '#7A4A2B' },
    { id: 46, dificuldade: 'facil', pergunta: 'Qual é a cor da coroa do Rei?', hex: '#F5C542' },
    { id: 47, dificuldade: 'facil', pergunta: 'Qual é a cor da camisa do Rei?', hex: '#3E75B6' },
    { id: 48, dificuldade: 'facil', pergunta: 'Qual é a cor do elixir?', hex: '#D946EF' },
    { id: 49, dificuldade: 'facil', pergunta: 'Qual é a cor da água do rio da Arena?', hex: '#3DB7D9' },
    { id: 50, dificuldade: 'facil', pergunta: 'Qual é a cor das Torres da Coroa?', hex: '#D8A23A' },
    { id: 51, dificuldade: 'media', pergunta: 'Qual é a cor da ponta da lança do Príncipe?', hex: '#DCE8F2' },
    { id: 52, dificuldade: 'media', pergunta: 'Qual é a cor da faixa azul do Príncipe?', hex: '#3975C6' },
    { id: 53, dificuldade: 'media', pergunta: 'Qual é a cor do pelo mais claro do cavalo do Príncipe?', hex: '#A96B3B' },
    { id: 54, dificuldade: 'media', pergunta: 'Qual é a cor do machado do Lenhador?', hex: '#8C9198' },
    { id: 55, dificuldade: 'media', pergunta: 'Qual é a cor da camisa do Lenhador?', hex: '#B83B3B' },
    { id: 56, dificuldade: 'media', pergunta: 'Qual é a cor do frasco de Fúria?', hex: '#7D3DB8' },
    { id: 57, dificuldade: 'media', pergunta: 'Qual é a cor do brilho ao redor da Fúria?', hex: '#D66CFF' },
    { id: 58, dificuldade: 'media', pergunta: 'Qual é a cor central da Bola de Fogo?', hex: '#FFD23F' },
    { id: 59, dificuldade: 'media', pergunta: 'Qual é a cor da borda das chamas da Bola de Fogo?', hex: '#E83B00' },
    { id: 60, dificuldade: 'media', pergunta: 'Qual é a cor da fumaça deixada pelo Feitiço de Gelo?', hex: '#C8F6FF' },
    { id: 61, dificuldade: 'media', pergunta: 'Qual é a cor da máscara do Príncipe das Trevas?', hex: '#161820' },
    { id: 62, dificuldade: 'media', pergunta: 'Qual é a cor do detalhe dourado do escudo do Príncipe das Trevas?', hex: '#C99A32' },
    { id: 63, dificuldade: 'media', pergunta: 'Qual é a cor do cabelo da Arqueira?', hex: '#8A542D' },
    { id: 64, dificuldade: 'media', pergunta: 'Qual é a cor da roupa da Arqueira?', hex: '#D95A8A' },
    { id: 65, dificuldade: 'media', pergunta: 'Qual é a cor das flechas das Arqueiras?', hex: '#C49A5A' },
    { id: 66, dificuldade: 'media', pergunta: 'Qual é a cor da armadura do P.E.K.K.A?', hex: '#303746' },
    { id: 67, dificuldade: 'media', pergunta: 'Qual é a cor dos olhos do P.E.K.K.A?', hex: '#C93AFF' },
    { id: 68, dificuldade: 'media', pergunta: 'Qual é a cor do fogo nos olhos do P.E.K.K.A?', hex: '#8B2CFF' },
    { id: 69, dificuldade: 'media', pergunta: 'Qual é a cor da roupa da Bandida?', hex: '#5A4B70' },
    { id: 70, dificuldade: 'media', pergunta: 'Qual é a cor da máscara da Bandida?', hex: '#2B2634' },
    { id: 71, dificuldade: 'media', pergunta: 'Qual é a cor do efeito do dash da Bandida?', hex: '#B8A5FF' },
    { id: 72, dificuldade: 'media', pergunta: 'Qual é a cor do cabelo do Cavaleiro Dourado?', hex: '#C98B3A' },
    { id: 73, dificuldade: 'media', pergunta: 'Qual é a cor da armadura do Cavaleiro Dourado?', hex: '#E3B84A' },
    { id: 74, dificuldade: 'media', pergunta: 'Qual é a cor do brilho da habilidade do Cavaleiro Dourado?', hex: '#FFD75A' },
    { id: 75, dificuldade: 'media', pergunta: 'Qual é a cor da capa do Mago?', hex: '#7436A5' },
    { id: 76, dificuldade: 'media', pergunta: 'Qual é a cor do cinto do Mago?', hex: '#E6A72F' },
    { id: 77, dificuldade: 'media', pergunta: 'Qual é a cor das faíscas do Mago Elétrico?', hex: '#69D9FF' },
    { id: 78, dificuldade: 'media', pergunta: 'Qual é a cor do raio do Dragão Infernal quando está carregando?', hex: '#FF9D24' },
    { id: 79, dificuldade: 'media', pergunta: 'Qual é a cor do brilho mais intenso no centro do raio do Dragão Infernal?', hex: '#FFE15C' },
    { id: 80, dificuldade: 'media', pergunta: 'Qual é a cor do fogo da Torre Inferno quando está totalmente carregada?', hex: '#FF2D00' },
    { id: 81, dificuldade: 'dificil', pergunta: 'Qual é a cor do centro do raio do Dragão Infernal no estágio máximo?', hex: '#FFF19A' },
    { id: 82, dificuldade: 'dificil', pergunta: 'Qual é a cor da borda externa do raio do Dragão Infernal?', hex: '#FF4A00' },
    { id: 83, dificuldade: 'dificil', pergunta: 'Qual é a cor da chama refletida na armadura do Dragão Infernal?', hex: '#FF7133' },
    { id: 84, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho do ataque carregado da Torre Inferno?', hex: '#FF7B00' },
    { id: 85, dificuldade: 'dificil', pergunta: 'Qual é a cor mais clara no centro da explosão da Bola de Fogo?', hex: '#FFF0A3' },
    { id: 86, dificuldade: 'dificil', pergunta: 'Qual é a cor mais escura da fumaça da Bola de Fogo?', hex: '#7A1D0A' },
    { id: 87, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho no centro do efeito da Fúria?', hex: '#E7A1FF' },
    { id: 88, dificuldade: 'dificil', pergunta: 'Qual é a cor da região mais escura do círculo da Fúria?', hex: '#632080' },
    { id: 89, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho do ataque do Mago Elétrico?', hex: '#D8F8FF' },
    { id: 90, dificuldade: 'dificil', pergunta: 'Qual é a cor mais intensa do raio do Mago Elétrico?', hex: '#39C8FF' },
    { id: 91, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho do ataque da Princesa?', hex: '#FFB7C8' },
    { id: 92, dificuldade: 'dificil', pergunta: 'Qual é a cor da chama do Dragão Bebê imediatamente antes da explosão?', hex: '#FFD33D' },
    { id: 93, dificuldade: 'dificil', pergunta: 'Qual é a cor da parte mais escura da armadura do P.E.K.K.A?', hex: '#171A24' },
    { id: 94, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho roxo dos olhos do P.E.K.K.A?', hex: '#B72CFF' },
    { id: 95, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho do ataque do Príncipe quando ele está em carga?', hex: '#D9E8FF' },
    { id: 96, dificuldade: 'dificil', pergunta: 'Qual é a cor do detalhe mais claro da armadura dourada do Príncipe?', hex: '#FFE37A' },
    { id: 97, dificuldade: 'dificil', pergunta: 'Qual é a cor da sombra mais escura da barba do Lenhador?', hex: '#3D2116' },
    { id: 98, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho produzido pelo ataque do Cavaleiro Dourado?', hex: '#FFF0A0' },
    { id: 99, dificuldade: 'dificil', pergunta: 'Qual é a cor da energia do ataque do Espírito Elétrico no momento do impacto?', hex: '#B5F5FF' },
    { id: 100, dificuldade: 'dificil', pergunta: 'Qual é a cor do centro luminoso da explosão do Relâmpago?', hex: '#F4F8FF' },
  ],
  marvel: [
    { id: 1, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da armadura do Homem de Ferro?', hex: '#B71C1C' },
    { id: 2, dificuldade: 'facil', pergunta: 'Qual é a cor predominante das partes metálicas douradas da armadura do Homem de Ferro?', hex: '#D4A72C' },
    { id: 3, dificuldade: 'facil', pergunta: 'Qual é a cor do reator no peito do Homem de Ferro?', hex: '#8DEBFF' },
    { id: 4, dificuldade: 'facil', pergunta: 'Qual é a cor dos olhos da armadura do Homem de Ferro?', hex: '#B8F3FF' },
    { id: 5, dificuldade: 'facil', pergunta: 'Qual é a cor das faixas externas do escudo do Capitão América?', hex: '#C62828' },
    { id: 6, dificuldade: 'facil', pergunta: 'Qual é a cor do círculo que fica ao redor da estrela no escudo do Capitão América?', hex: '#174A8B' },
    { id: 7, dificuldade: 'facil', pergunta: 'Qual é a cor da estrela no centro do escudo do Capitão América?', hex: '#F2F2F2' },
    { id: 8, dificuldade: 'facil', pergunta: 'Qual é a cor da pele do Hulk?', hex: '#4CAF50' },
    { id: 9, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo do Hulk?', hex: '#181818' },
    { id: 10, dificuldade: 'facil', pergunta: 'Qual é a cor da calça do Hulk?', hex: '#6A1B9A' },
    { id: 11, dificuldade: 'facil', pergunta: 'Qual é a cor do martelo de Thor?', hex: '#8D969D' },
    { id: 12, dificuldade: 'facil', pergunta: 'Qual é a cor da capa de Thor?', hex: '#8B0000' },
    { id: 13, dificuldade: 'facil', pergunta: 'Qual é a cor dos raios produzidos por Thor?', hex: '#DDF7FF' },
    { id: 14, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do uniforme do Homem-Aranha?', hex: '#C62828' },
    { id: 15, dificuldade: 'facil', pergunta: 'Qual é a cor predominante das áreas laterais do uniforme clássico do Homem-Aranha?', hex: '#1565C0' },
    { id: 16, dificuldade: 'facil', pergunta: 'Qual é a cor das lentes da máscara do Homem-Aranha?', hex: '#F4F4F4' },
    { id: 17, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do uniforme da Viúva Negra?', hex: '#171717' },
    { id: 18, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do cabelo da Viúva Negra em Os Vingadores?', hex: '#B34A35' },
    { id: 19, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa do Gavião Arqueiro em Os Vingadores?', hex: '#25282D' },
    { id: 20, dificuldade: 'facil', pergunta: 'Qual é a cor da haste das flechas do Gavião Arqueiro?', hex: '#8B5A2B' },
    { id: 21, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da capa do Doutor Estranho?', hex: '#9E1B32' },
    { id: 22, dificuldade: 'facil', pergunta: 'Qual é a cor dos efeitos dos portais criados pelo Doutor Estranho?', hex: '#F5A623' },
    { id: 23, dificuldade: 'facil', pergunta: 'Qual é a cor da energia utilizada pela Feiticeira Escarlate?', hex: '#D41446' },
    { id: 24, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do traje do Pantera Negra?', hex: '#111111' },
    { id: 25, dificuldade: 'facil', pergunta: 'Qual é a cor das linhas luminosas do traje do Pantera Negra?', hex: '#5B4B9A' },
    { id: 26, dificuldade: 'facil', pergunta: 'Qual é a cor da pele da Gamora?', hex: '#4CAF50' },
    { id: 27, dificuldade: 'facil', pergunta: 'Qual é a cor da pele do Drax?', hex: '#78909C' },
    { id: 28, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo do Groot?', hex: '#795548' },
    { id: 29, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do pelo do Rocket?', hex: '#8D6748' },
    { id: 30, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da jaqueta do Senhor das Estrelas?', hex: '#263238' },
    { id: 31, dificuldade: 'facil', pergunta: 'Qual é a cor da pele do Thanos?', hex: '#6A3D9A' },
    { id: 32, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da armadura de Thanos?', hex: '#5D4A3A' },
    { id: 33, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da Manopla do Infinito?', hex: '#C9A227' },
    { id: 34, dificuldade: 'facil', pergunta: 'Qual é a cor da Joia que fica dentro do Tesseract?', hex: '#29B6F6' },
    { id: 35, dificuldade: 'facil', pergunta: 'Qual é a cor da Joia que estava no cetro de Loki?', hex: '#FFD740' },
    { id: 36, dificuldade: 'facil', pergunta: 'Qual é a cor da Joia utilizada por Ronan?', hex: '#7B1FA2' },
    { id: 37, dificuldade: 'facil', pergunta: 'Qual é a cor da Joia usada pelo Doutor Estranho para manipular o tempo?', hex: '#43A047' },
    { id: 38, dificuldade: 'facil', pergunta: 'Qual é a cor da Joia usada por Thanos para alterar a realidade?', hex: '#D32F2F' },
    { id: 39, dificuldade: 'facil', pergunta: 'Qual é a cor da Joia encontrada em Vormir?', hex: '#FF9800' },
    { id: 40, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do uniforme de Loki?', hex: '#1B5E20' },
    { id: 41, dificuldade: 'facil', pergunta: 'Qual é a cor dos chifres do capacete de Loki?', hex: '#C9A227' },
    { id: 42, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do uniforme da Capitã Marvel?', hex: '#0D47A1' },
    { id: 43, dificuldade: 'facil', pergunta: 'Qual é a cor do símbolo no peito da Capitã Marvel?', hex: '#E0B51A' },
    { id: 44, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do traje do Homem-Formiga?', hex: '#B71C1C' },
    { id: 45, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do traje da Vespa?', hex: '#D9A514' },
    { id: 46, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do uniforme do Soldado Invernal?', hex: '#455A64' },
    { id: 47, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do uniforme do Falcão?', hex: '#20252A' },
    { id: 48, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo do Visão?', hex: '#B52B2B' },
    { id: 49, dificuldade: 'facil', pergunta: 'Qual é a cor da Joia que aparece na testa do Visão?', hex: '#F6D94A' },
    { id: 50, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da armadura do Máquina de Combate?', hex: '#4A4F55' },
    { id: 51, dificuldade: 'media', pergunta: 'Qual é a cor do brilho do reator Arc do Homem de Ferro quando ele está totalmente carregado?', hex: '#A8F3FF' },
    { id: 52, dificuldade: 'media', pergunta: 'Qual é a cor predominante das placas metálicas da Mark 42?', hex: '#C99A2E' },
    { id: 53, dificuldade: 'media', pergunta: 'Qual é a cor predominante da armadura Hulkbuster?', hex: '#8A1F1F' },
    { id: 54, dificuldade: 'media', pergunta: 'Qual é a cor das luzes dos olhos da Hulkbuster?', hex: '#8BE9FF' },
    { id: 55, dificuldade: 'media', pergunta: 'Qual é a cor predominante do uniforme usado por Steve Rogers em O Soldado Invernal?', hex: '#1E3A5F' },
    { id: 56, dificuldade: 'media', pergunta: 'Qual é a cor da estrela no peito do uniforme usado por Steve Rogers em O Soldado Invernal?', hex: '#D9DDE2' },
    { id: 57, dificuldade: 'media', pergunta: 'Qual é a cor predominante da armadura de Thor em Ragnarok?', hex: '#37474F' },
    { id: 58, dificuldade: 'media', pergunta: 'Qual é a cor predominante da armadura usada por Hela?', hex: '#181818' },
    { id: 59, dificuldade: 'media', pergunta: 'Qual é a cor do brilho das armas criadas por Hela?', hex: '#43A047' },
    { id: 60, dificuldade: 'media', pergunta: 'Qual é a cor predominante do Bifrost quando ele está ativo?', hex: '#6DD5FF' },
    { id: 61, dificuldade: 'media', pergunta: 'Qual é a cor predominante das teias disparadas pelo Homem-Aranha?', hex: '#E1E5E8' },
    { id: 62, dificuldade: 'media', pergunta: 'Qual é a cor das lentes do traje Aranha de Ferro?', hex: '#63D8FF' },
    { id: 63, dificuldade: 'media', pergunta: 'Qual é a cor predominante das pernas mecânicas do traje Aranha de Ferro?', hex: '#B71C1C' },
    { id: 64, dificuldade: 'media', pergunta: 'Qual é a cor predominante do traje usado pelo Homem-Aranha durante sua missão em Berlim?', hex: '#111318' },
    { id: 65, dificuldade: 'media', pergunta: 'Qual é a cor das faíscas produzidas pelos feitiços do Doutor Estranho?', hex: '#FFAA2B' },
    { id: 66, dificuldade: 'media', pergunta: 'Qual é a cor predominante das páginas do Darkhold?', hex: '#30201E' },
    { id: 67, dificuldade: 'media', pergunta: 'Qual é a cor do brilho mágico usado por Wanda em Multiverso da Loucura?', hex: '#D41446' },
    { id: 68, dificuldade: 'media', pergunta: 'Qual é a cor predominante do traje de batalha da Feiticeira Escarlate?', hex: '#8E1027' },
    { id: 69, dificuldade: 'media', pergunta: 'Qual é a cor predominante do capacete de Mysterio?', hex: '#2F3437' },
    { id: 70, dificuldade: 'media', pergunta: 'Qual é a cor predominante das ilusões criadas por Mysterio?', hex: '#4CAF50' },
    { id: 71, dificuldade: 'media', pergunta: 'Qual é a cor predominante do traje de Killmonger durante a batalha final?', hex: '#151515' },
    { id: 72, dificuldade: 'media', pergunta: 'Qual é a cor predominante das linhas luminosas do traje do Pantera Negra durante a batalha?', hex: '#6B55A5' },
    { id: 73, dificuldade: 'media', pergunta: 'Qual é a cor do brilho produzido pelo traje do Pantera Negra ao absorver impactos?', hex: '#7E57C2' },
    { id: 74, dificuldade: 'media', pergunta: 'Qual é a cor predominante do traje usado por Shuri quando assume o manto do Pantera Negra?', hex: '#111111' },
    { id: 75, dificuldade: 'media', pergunta: 'Qual é a cor predominante da armadura do Homem-Formiga?', hex: '#9E1B24' },
    { id: 76, dificuldade: 'media', pergunta: 'Qual é a cor das partículas liberadas pelos equipamentos de Hank Pym?', hex: '#E8B52E' },
    { id: 77, dificuldade: 'media', pergunta: 'Qual é a cor predominante do traje de batalha do Senhor das Estrelas?', hex: '#263238' },
    { id: 78, dificuldade: 'media', pergunta: 'Qual é a cor da energia disparada pelos blasters do Senhor das Estrelas?', hex: '#FFB52E' },
    { id: 79, dificuldade: 'media', pergunta: 'Qual é a cor predominante da roupa de batalha da Gamora?', hex: '#20242A' },
    { id: 80, dificuldade: 'media', pergunta: 'Qual é a cor predominante da armadura de Thanos durante a batalha em Wakanda?', hex: '#5C4738' },
    { id: 81, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho no centro do Tesseract quando ele é ativado?', hex: '#9BEFFF' },
    { id: 82, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho emitido pelo cetro de Loki quando seu poder é utilizado?', hex: '#FFE45C' },
    { id: 83, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho que envolve a Joia do Tempo quando o Doutor Estranho a utiliza?', hex: '#7BCB3A' },
    { id: 84, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho produzido pela Joia do Poder quando Ronan utiliza seu poder?', hex: '#8E24AA' },
    { id: 85, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho produzido pela Joia da Realidade quando Thanos altera a matéria?', hex: '#D32F2F' },
    { id: 86, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho associado à Joia da Alma em Vormir?', hex: '#FF8C00' },
    { id: 87, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante das faíscas usadas pelo Doutor Estranho para abrir um portal?', hex: '#F6A623' },
    { id: 88, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho das duplicações mágicas criadas pelo Doutor Estranho?', hex: '#FFB52E' },
    { id: 89, dificuldade: 'dificil', pergunta: 'Qual é a cor mais intensa da energia utilizada por Wanda contra Thanos?', hex: '#FF1744' },
    { id: 90, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho da energia utilizada por Wanda para destruir o Darkhold?', hex: '#D5003D' },
    { id: 91, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho que aparece ao redor do Homem-Aranha quando seu sentido-aranha é representado visualmente?', hex: '#FFD54F' },
    { id: 92, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante das partículas luminosas do Reino Quântico?', hex: '#7E57C2' },
    { id: 93, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da energia liberada pela Capitã Marvel quando seus poderes estão no máximo?', hex: '#64D8FF' },
    { id: 94, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho que aparece nos olhos da Capitã Marvel quando seus poderes estão ativos?', hex: '#A8F0FF' },
    { id: 95, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da energia que envolve Thanos quando ele utiliza várias Joias do Infinito?', hex: '#B56CFF' },
    { id: 96, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho produzido no momento em que Thanos realiza o estalo?', hex: '#FFF1B8' },
    { id: 97, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho que percorre a Manopla do Infinito durante o estalo?', hex: '#C084FC' },
    { id: 98, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da energia que percorre a armadura de Tony Stark quando ele utiliza as Joias do Infinito?', hex: '#FFD54F' },
    { id: 99, dificuldade: 'dificil', pergunta: 'Qual é a cor do brilho que aparece na armadura de Tony Stark após utilizar as Joias do Infinito?', hex: '#FFB74D' },
    { id: 100, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da energia liberada pelo ataque final de Thor contra Thanos?', hex: '#DDF7FF' },
  ],
  disney: [
    { id: 1, dificuldade: 'facil', pergunta: 'Qual é a cor da juba de Simba quando adulto?', hex: '#8B542F', fonte: 'O Rei Leão' },
    { id: 2, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo de Simba?', hex: '#D99A3D', fonte: 'O Rei Leão' },
    { id: 3, dificuldade: 'facil', pergunta: 'Qual é a cor do pelo de Timão?', hex: '#C98B52', fonte: 'O Rei Leão' },
    { id: 4, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo de Pumba?', hex: '#9B6A52', fonte: 'O Rei Leão' },
    { id: 5, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Rafiki?', hex: '#8A8C91', fonte: 'O Rei Leão' },
    { id: 6, dificuldade: 'facil', pergunta: 'Qual é a cor da roupa de Aladdin?', hex: '#6C4AA0', fonte: 'Aladdin' },
    { id: 7, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo do Gênio?', hex: '#1685A8', fonte: 'Aladdin' },
    { id: 8, dificuldade: 'facil', pergunta: 'Qual é a cor do vestido de Jasmine?', hex: '#55C7C9', fonte: 'Aladdin' },
    { id: 9, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do tapete mágico?', hex: '#B52D32', fonte: 'Aladdin' },
    { id: 10, dificuldade: 'facil', pergunta: 'Qual é a cor da roupa de Jafar?', hex: '#5B2148', fonte: 'Aladdin' },
    { id: 11, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo de Ariel?', hex: '#B93632', fonte: 'A Pequena Sereia' },
    { id: 12, dificuldade: 'facil', pergunta: 'Qual é a cor da cauda de Ariel?', hex: '#20A88A', fonte: 'A Pequena Sereia' },
    { id: 13, dificuldade: 'facil', pergunta: 'Qual é a cor do top de Ariel?', hex: '#7B4AA0', fonte: 'A Pequena Sereia' },
    { id: 14, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo de Sebastião?', hex: '#D93632', fonte: 'A Pequena Sereia' },
    { id: 15, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo de Linguado?', hex: '#F2D34F', fonte: 'A Pequena Sereia' },
    { id: 16, dificuldade: 'facil', pergunta: 'Qual é a cor do vestido de Bela no baile?', hex: '#F2C84B', fonte: 'A Bela e a Fera' },
    { id: 17, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da pelagem da Fera?', hex: '#7B563F', fonte: 'A Bela e a Fera' },
    { id: 18, dificuldade: 'facil', pergunta: 'Qual é a cor da rosa encantada?', hex: '#C92D3F', fonte: 'A Bela e a Fera' },
    { id: 19, dificuldade: 'facil', pergunta: 'Qual é a cor da xícara de Chip?', hex: '#E8E2D2', fonte: 'A Bela e a Fera' },
    { id: 20, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Mulan no início do filme?', hex: '#D85A75', fonte: 'Mulan' },
    { id: 21, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo de Mushu?', hex: '#D53A2F', fonte: 'Mulan' },
    { id: 22, dificuldade: 'facil', pergunta: 'Qual é a cor das escamas de Mushu?', hex: '#E0A52F', fonte: 'Mulan' },
    { id: 23, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo de Hércules?', hex: '#D79A42', fonte: 'Hércules' },
    { id: 24, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Hércules?', hex: '#6B82A8', fonte: 'Hércules' },
    { id: 25, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo de Hades?', hex: '#2D8C8B', fonte: 'Hércules' },
    { id: 26, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Tarzan?', hex: '#6E9B49', fonte: 'Tarzan' },
    { id: 27, dificuldade: 'facil', pergunta: 'Qual é a cor do pelo de Kala?', hex: '#5D5148', fonte: 'Tarzan' },
    { id: 28, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do vestido de Pocahontas?', hex: '#A56A4C', fonte: 'Pocahontas' },
    { id: 29, dificuldade: 'facil', pergunta: 'Qual é a cor do pelo de Meeko?', hex: '#6D5140', fonte: 'Pocahontas' },
    { id: 30, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Kuzco?', hex: '#7A3E91', fonte: 'A Nova Onda do Imperador' },
    { id: 31, dificuldade: 'facil', pergunta: 'Qual é a cor do pelo de Kronk?', hex: '#D6A03A', fonte: 'A Nova Onda do Imperador' },
    { id: 32, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo de Stitch?', hex: '#4C8DCC', fonte: 'Lilo & Stitch' },
    { id: 33, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Lilo?', hex: '#D9363E', fonte: 'Lilo & Stitch' },
    { id: 34, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do pelo de Kenai como urso?', hex: '#7B4F32', fonte: 'Irmão Urso' },
    { id: 35, dificuldade: 'facil', pergunta: 'Qual é a cor do vestido de Tiana?', hex: '#76B852', fonte: 'A Princesa e o Sapo' },
    { id: 36, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do traje do Dr. Facilier?', hex: '#25203A', fonte: 'A Princesa e o Sapo' },
    { id: 37, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo de Rapunzel?', hex: '#D9A441', fonte: 'Enrolados' },
    { id: 38, dificuldade: 'facil', pergunta: 'Qual é a cor do vestido de Rapunzel?', hex: '#A56BB5', fonte: 'Enrolados' },
    { id: 39, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo de Pascal?', hex: '#69A84F', fonte: 'Enrolados' },
    { id: 40, dificuldade: 'facil', pergunta: 'Qual é a cor do vestido de Elsa?', hex: '#8ED8E8', fonte: 'Frozen' },
    { id: 41, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo de Elsa?', hex: '#D7D7E4', fonte: 'Frozen' },
    { id: 42, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Anna?', hex: '#7A3159', fonte: 'Frozen' },
    { id: 43, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo de Olaf?', hex: '#F1EEE5', fonte: 'Frozen' },
    { id: 44, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Moana?', hex: '#C65B3C', fonte: 'Moana' },
    { id: 45, dificuldade: 'facil', pergunta: 'Qual é a cor da pele de Maui?', hex: '#6D412F', fonte: 'Moana' },
    { id: 46, dificuldade: 'facil', pergunta: 'Qual é a cor dos óculos de Mirabel?', hex: '#6B4A35', fonte: 'Encanto' },
    { id: 47, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do vestido de Mirabel?', hex: '#6A3C78', fonte: 'Encanto' },
    { id: 48, dificuldade: 'facil', pergunta: 'Qual é a cor do pelo de Judy Hopps?', hex: '#B7B9B1', fonte: 'Zootopia' },
    { id: 49, dificuldade: 'facil', pergunta: 'Qual é a cor do pelo de Nick Wilde?', hex: '#C56A3A', fonte: 'Zootopia' },
    { id: 50, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Ralph?', hex: '#7A4B35', fonte: 'Detona Ralph' },
    { id: 51, dificuldade: 'media', pergunta: 'Qual é a cor predominante do uniforme de Woody?', hex: '#D8B43A', fonte: 'Toy Story' },
    { id: 52, dificuldade: 'media', pergunta: 'Qual é a cor do lenço de Woody?', hex: '#8C2026', fonte: 'Toy Story' },
    { id: 53, dificuldade: 'media', pergunta: 'Qual é a cor predominante do traje de Buzz Lightyear?', hex: '#E8E8DF', fonte: 'Toy Story' },
    { id: 54, dificuldade: 'media', pergunta: 'Qual é a cor das asas de Buzz Lightyear?', hex: '#7BB8A0', fonte: 'Toy Story' },
    { id: 55, dificuldade: 'media', pergunta: 'Qual é a cor do corpo de Sulley?', hex: '#4D9AB5', fonte: 'Monstros S.A.' },
    { id: 56, dificuldade: 'media', pergunta: 'Qual é a cor das manchas do corpo de Sulley?', hex: '#A66BB7', fonte: 'Monstros S.A.' },
    { id: 57, dificuldade: 'media', pergunta: 'Qual é a cor do corpo de Mike Wazowski?', hex: '#75B943', fonte: 'Monstros S.A.' },
    { id: 58, dificuldade: 'media', pergunta: 'Qual é a cor predominante do corpo de Nemo?', hex: '#F07832', fonte: 'Procurando Nemo' },
    { id: 59, dificuldade: 'media', pergunta: 'Qual é a cor das listras do corpo de Nemo?', hex: '#F2F0E8', fonte: 'Procurando Nemo' },
    { id: 60, dificuldade: 'media', pergunta: 'Qual é a cor predominante do corpo de Dory?', hex: '#2385C5', fonte: 'Procurando Nemo' },
    { id: 61, dificuldade: 'media', pergunta: 'Qual é a cor predominante do uniforme do Sr. Incrível?', hex: '#D72F2F', fonte: 'Os Incríveis' },
    { id: 62, dificuldade: 'media', pergunta: 'Qual é a cor da máscara do Sr. Incrível?', hex: '#F0A52B', fonte: 'Os Incríveis' },
    { id: 63, dificuldade: 'media', pergunta: 'Qual é a cor predominante do uniforme da Mulher-Elástica?', hex: '#D72F2F', fonte: 'Os Incríveis' },
    { id: 64, dificuldade: 'media', pergunta: 'Qual é a cor predominante do uniforme do Gelado?', hex: '#6FB9D6', fonte: 'Os Incríveis' },
    { id: 65, dificuldade: 'media', pergunta: 'Qual é a cor do corpo de Relâmpago McQueen?', hex: '#D92727', fonte: 'Carros' },
    { id: 66, dificuldade: 'media', pergunta: 'Qual é a cor do corpo de Mate?', hex: '#A66A3F', fonte: 'Carros' },
    { id: 67, dificuldade: 'media', pergunta: 'Qual é a cor do pelo de Remy?', hex: '#8A6A54', fonte: 'Ratatouille' },
    { id: 68, dificuldade: 'media', pergunta: 'Qual é a cor predominante do corpo de WALL-E?', hex: '#B08A3C', fonte: 'WALL-E' },
    { id: 69, dificuldade: 'media', pergunta: 'Qual é a cor predominante da casa de Carl?', hex: '#D3A34A', fonte: 'Up' },
    { id: 70, dificuldade: 'media', pergunta: 'Qual é a cor dos balões presos à casa de Carl?', hex: '#E64B45', fonte: 'Up' },
    { id: 71, dificuldade: 'media', pergunta: 'Qual é a cor do cabelo de Merida?', hex: '#D45A25', fonte: 'Valente' },
    { id: 72, dificuldade: 'media', pergunta: 'Qual é a cor predominante do vestido de Merida?', hex: '#315B48', fonte: 'Valente' },
    { id: 73, dificuldade: 'media', pergunta: 'Qual é a cor do corpo de Mike Wazowski?', hex: '#78B943', fonte: 'Universidade Monstros' },
    { id: 74, dificuldade: 'media', pergunta: 'Qual é a cor predominante do pelo de Sulley?', hex: '#4C8FB1', fonte: 'Universidade Monstros' },
    { id: 75, dificuldade: 'media', pergunta: 'Qual é a cor do corpo de Alegria?', hex: '#F4C62E', fonte: 'Divertida Mente' },
    { id: 76, dificuldade: 'media', pergunta: 'Qual é a cor do corpo de Tristeza?', hex: '#416FC1', fonte: 'Divertida Mente' },
    { id: 77, dificuldade: 'media', pergunta: 'Qual é a cor do corpo de Raiva?', hex: '#D83A2E', fonte: 'Divertida Mente' },
    { id: 78, dificuldade: 'media', pergunta: 'Qual é a cor do corpo de Nojinho?', hex: '#65B64A', fonte: 'Divertida Mente' },
    { id: 79, dificuldade: 'media', pergunta: 'Qual é a cor predominante da roupa de Miguel?', hex: '#E8E0D3', fonte: 'Viva: A Vida é uma Festa' },
    { id: 80, dificuldade: 'media', pergunta: 'Qual é a cor predominante da pele de Héctor?', hex: '#D5A15C', fonte: 'Viva: A Vida é uma Festa' },
    { id: 81, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da juba de Scar?', hex: '#30251F', fonte: 'O Rei Leão' },
    { id: 82, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do traje de dança usado por Jasmine?', hex: '#49B9B8', fonte: 'Aladdin' },
    { id: 83, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do vestido de Ursula?', hex: '#33254D', fonte: 'A Pequena Sereia' },
    { id: 84, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante das roupas de Gaston?', hex: '#304F85', fonte: 'A Bela e a Fera' },
    { id: 85, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da armadura usada pelos soldados chineses?', hex: '#5A6470', fonte: 'Mulan' },
    { id: 86, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da chama que envolve Hades?', hex: '#42A8A0', fonte: 'Hércules' },
    { id: 87, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do traje de Stitch quando ele está disfarçado de Elvis?', hex: '#1B2638', fonte: 'Lilo & Stitch' },
    { id: 88, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante das sombras mágicas do Dr. Facilier?', hex: '#241B36', fonte: 'A Princesa e o Sapo' },
    { id: 89, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante das lanternas lançadas no céu?', hex: '#F4A13A', fonte: 'Enrolados' },
    { id: 90, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do castelo de gelo de Elsa?', hex: '#8FD8EA', fonte: 'Frozen' },
    { id: 91, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do coração de Te Fiti?', hex: '#6FCB63', fonte: 'Moana' },
    { id: 92, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da lava de Te Kā?', hex: '#D94A32', fonte: 'Moana' },
    { id: 93, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante das flores criadas por Isabela?', hex: '#D64D9A', fonte: 'Encanto' },
    { id: 94, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do vestido de Isabela?', hex: '#C56BC5', fonte: 'Encanto' },
    { id: 95, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do uniforme policial de Judy?', hex: '#4E83A5', fonte: 'Zootopia' },
    { id: 96, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do traje de Jessie?', hex: '#D94B35', fonte: 'Toy Story' },
    { id: 97, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da porta do quarto de Boo?', hex: '#D86A94', fonte: 'Monstros S.A.' },
    { id: 98, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do símbolo no peito dos Incríveis?', hex: '#F0A52B', fonte: 'Os Incríveis' },
    { id: 99, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante das ilhas de personalidade de Riley?', hex: '#6D5AA8', fonte: 'Divertida Mente' },
    { id: 100, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante das flores que formam a ponte entre os mundos?', hex: '#F2A63B', fonte: 'Viva: A Vida é uma Festa' },
  ],
  futebol: [
    { id: 1, dificuldade: 'facil', pergunta: 'Qual é a cor predominante das letras no escudo do Flamengo?', hex: '#000000', fonte: 'Flamengo' },
    { id: 2, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do círculo externo do escudo do Corinthians?', hex: '#000000', fonte: 'Corinthians' },
    { id: 3, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do círculo externo do escudo do Palmeiras?', hex: '#006437', fonte: 'Palmeiras' },
    { id: 4, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da faixa central do escudo do São Paulo?', hex: '#E31B23', fonte: 'São Paulo' },
    { id: 5, dificuldade: 'facil', pergunta: 'Qual é a cor predominante das faixas verticais do escudo do Santos?', hex: '#000000', fonte: 'Santos' },
    { id: 6, dificuldade: 'facil', pergunta: 'Qual é a cor da cruz central do escudo do Vasco?', hex: '#000000', fonte: 'Vasco da Gama' },
    { id: 7, dificuldade: 'facil', pergunta: 'Qual é a cor da estrela no centro do escudo do Botafogo?', hex: '#000000', fonte: 'Botafogo' },
    { id: 8, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da faixa central do escudo do Fluminense?', hex: '#7A1730', fonte: 'Fluminense' },
    { id: 9, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do círculo externo do escudo do Grêmio?', hex: '#0B3D91', fonte: 'Grêmio' },
    { id: 10, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do círculo externo do escudo do Internacional?', hex: '#D71920', fonte: 'Internacional' },
    { id: 11, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do círculo externo do escudo do Cruzeiro?', hex: '#005CA9', fonte: 'Cruzeiro' },
    { id: 12, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do fundo do escudo do Atlético Mineiro?', hex: '#000000', fonte: 'Atlético Mineiro' },
    { id: 13, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do círculo externo do escudo do Bahia?', hex: '#005CA9', fonte: 'Bahia' },
    { id: 14, dificuldade: 'facil', pergunta: 'Qual é a cor predominante das faixas verticais do escudo do Sport?', hex: '#D71920', fonte: 'Sport' },
    { id: 15, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da parte central do escudo do Fortaleza?', hex: '#D71920', fonte: 'Fortaleza' },
    { id: 16, dificuldade: 'facil', pergunta: 'Qual é a cor predominante das faixas do escudo do Ceará?', hex: '#000000', fonte: 'Ceará' },
    { id: 17, dificuldade: 'facil', pergunta: 'Qual é a cor predominante das faixas diagonais do escudo do Athletico?', hex: '#D71920', fonte: 'Athletico Paranaense' },
    { id: 18, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do círculo externo do escudo do Coritiba?', hex: '#006B3F', fonte: 'Coritiba' },
    { id: 19, dificuldade: 'facil', pergunta: 'Qual é a cor predominante das listras do escudo do Vitória?', hex: '#D71920', fonte: 'Vitória' },
    { id: 20, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do fundo do escudo do Bragantino?', hex: '#D71920', fonte: 'Bragantino' },
    { id: 21, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do círculo central do escudo da Seleção Brasileira?', hex: '#F6C800', fonte: 'Seleção Brasileira' },
    { id: 22, dificuldade: 'facil', pergunta: 'Qual é a cor predominante das faixas verticais do escudo da Argentina?', hex: '#75AADB', fonte: 'Seleção Argentina' },
    { id: 23, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da águia no escudo da Alemanha?', hex: '#000000', fonte: 'Seleção Alemã' },
    { id: 24, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do galo no escudo da França?', hex: '#0055A4', fonte: 'Seleção Francesa' },
    { id: 25, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da cruz no centro do escudo de Portugal?', hex: '#D71920', fonte: 'Seleção Portuguesa' },
    { id: 26, dificuldade: 'media', pergunta: 'Qual é a cor predominante das letras CRF no centro do escudo do Flamengo?', hex: '#000000', fonte: 'Flamengo' },
    { id: 27, dificuldade: 'media', pergunta: 'Qual é a cor predominante do barco representado no escudo do Corinthians?', hex: '#000000', fonte: 'Corinthians' },
    { id: 28, dificuldade: 'media', pergunta: 'Qual é a cor predominante da letra no centro do escudo do Palmeiras?', hex: '#FFFFFF', fonte: 'Palmeiras' },
    { id: 29, dificuldade: 'media', pergunta: 'Qual é a cor predominante da parte superior do escudo do São Paulo?', hex: '#000000', fonte: 'São Paulo' },
    { id: 30, dificuldade: 'media', pergunta: 'Qual é a cor predominante da bola representada no escudo do Santos?', hex: '#000000', fonte: 'Santos' },
    { id: 31, dificuldade: 'media', pergunta: 'Qual é a cor predominante da caravela representada no escudo do Vasco?', hex: '#000000', fonte: 'Vasco da Gama' },
    { id: 32, dificuldade: 'media', pergunta: 'Qual é a cor predominante das letras do escudo do Fluminense?', hex: '#FFFFFF', fonte: 'Fluminense' },
    { id: 33, dificuldade: 'media', pergunta: 'Qual é a cor predominante da faixa central do escudo do Grêmio?', hex: '#000000', fonte: 'Grêmio' },
    { id: 34, dificuldade: 'media', pergunta: 'Qual é a cor predominante das letras no centro do escudo do Internacional?', hex: '#FFFFFF', fonte: 'Internacional' },
    { id: 35, dificuldade: 'media', pergunta: 'Qual é a cor predominante das estrelas no centro do escudo do Cruzeiro?', hex: '#FFFFFF', fonte: 'Cruzeiro' },
    { id: 36, dificuldade: 'media', pergunta: 'Qual é a cor predominante da estrela acima do escudo do Atlético Mineiro?', hex: '#F6C800', fonte: 'Atlético Mineiro' },
    { id: 37, dificuldade: 'media', pergunta: 'Qual é a cor predominante da faixa diagonal no escudo do Bahia?', hex: '#D71920', fonte: 'Bahia' },
    { id: 38, dificuldade: 'media', pergunta: 'Qual é a cor predominante das listras verticais do escudo do Fortaleza?', hex: '#0055A4', fonte: 'Fortaleza' },
    { id: 39, dificuldade: 'media', pergunta: 'Qual é a cor predominante da borda do escudo do Botafogo?', hex: '#000000', fonte: 'Botafogo' },
    { id: 40, dificuldade: 'media', pergunta: 'Qual é a cor predominante da faixa que atravessa o escudo da Seleção Brasileira?', hex: '#FFFFFF', fonte: 'Seleção Brasileira' },
    { id: 41, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do detalhe central acima das faixas no escudo da Argentina?', hex: '#F6C800', fonte: 'Seleção Argentina' },
    { id: 42, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da coroa no escudo da Espanha?', hex: '#F6C800', fonte: 'Seleção Espanhola' },
    { id: 43, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante das três coroas no escudo da Inglaterra?', hex: '#D71920', fonte: 'Seleção Inglesa' },
    { id: 44, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da faixa central da bandeira no escudo da Itália?', hex: '#FFFFFF', fonte: 'Seleção Italiana' },
    { id: 45, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do sol no escudo do Uruguai?', hex: '#F6C800', fonte: 'Seleção Uruguaia' },
    { id: 46, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da águia no escudo do México?', hex: '#5B3924', fonte: 'Seleção Mexicana' },
    { id: 47, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do símbolo central no escudo da Seleção Japonesa?', hex: '#D71920', fonte: 'Seleção Japonesa' },
    { id: 48, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do padrão de quadrados no escudo da Croácia?', hex: '#D71920', fonte: 'Seleção Croata' },
    { id: 49, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da estrela no centro do escudo do Marrocos?', hex: '#D71920', fonte: 'Seleção Marroquina' },
    { id: 50, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do leão no escudo da Seleção Holandesa?', hex: '#F28C28', fonte: 'Seleção Holandesa' },
  ],
  cartoon: [
    { id: 1, dificuldade: 'facil', pergunta: 'Qual é a cor do vestido da Florzinha?', hex: '#E94B5F', fonte: 'As Meninas Superpoderosas' },
    { id: 2, dificuldade: 'facil', pergunta: 'Qual é a cor do vestido da Lindinha?', hex: '#5DADE2', fonte: 'As Meninas Superpoderosas' },
    { id: 3, dificuldade: 'facil', pergunta: 'Qual é a cor do vestido da Docinho?', hex: '#55B947', fonte: 'As Meninas Superpoderosas' },
    { id: 4, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo da Florzinha?', hex: '#E84A35', fonte: 'As Meninas Superpoderosas' },
    { id: 5, dificuldade: 'facil', pergunta: 'Qual é a cor do pelo do Macaco Louco?', hex: '#704B91', fonte: 'As Meninas Superpoderosas' },
    { id: 6, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo de Dexter?', hex: '#E46B2E', fonte: 'O Laboratório de Dexter' },
    { id: 7, dificuldade: 'facil', pergunta: 'Qual é a cor da armação dos óculos de Dexter?', hex: '#4A3026', fonte: 'O Laboratório de Dexter' },
    { id: 8, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo de Dee Dee?', hex: '#E9B4D0', fonte: 'O Laboratório de Dexter' },
    { id: 9, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo de Coragem?', hex: '#C98AA5', fonte: 'Coragem, o Cão Covarde' },
    { id: 10, dificuldade: 'facil', pergunta: 'Qual é a cor do suéter de Muriel?', hex: '#F2B84B', fonte: 'Coragem, o Cão Covarde' },
    { id: 11, dificuldade: 'facil', pergunta: 'Qual é a cor da camisa de Edd?', hex: '#3D9B72', fonte: 'Du, Dudu e Edu' },
    { id: 12, dificuldade: 'facil', pergunta: 'Qual é a cor da camisa de Eddy?', hex: '#E6B83F', fonte: 'Du, Dudu e Edu' },
    { id: 13, dificuldade: 'facil', pergunta: 'Qual é a cor da camisa de Ed?', hex: '#7C3F91', fonte: 'Du, Dudu e Edu' },
    { id: 14, dificuldade: 'facil', pergunta: 'Qual é a cor do vestido de Mandy?', hex: '#E8A6B9', fonte: 'As Terríveis Aventuras de Billy e Mandy' },
    { id: 15, dificuldade: 'facil', pergunta: 'Qual é a cor da camisa de Billy?', hex: '#F2C84B', fonte: 'As Terríveis Aventuras de Billy e Mandy' },
    { id: 16, dificuldade: 'facil', pergunta: 'Qual é a cor da gravata de Billy?', hex: '#7A3E91', fonte: 'As Terríveis Aventuras de Billy e Mandy' },
    { id: 17, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo de Johnny Bravo?', hex: '#E2A52F', fonte: 'Johnny Bravo' },
    { id: 18, dificuldade: 'facil', pergunta: 'Qual é a cor da camisa de Johnny Bravo?', hex: '#1D6FA5', fonte: 'Johnny Bravo' },
    { id: 19, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da pele de Quatro Braços?', hex: '#B83B32', fonte: 'Ben 10' },
    { id: 20, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de XLR8?', hex: '#202B35', fonte: 'Ben 10' },
    { id: 21, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Diamante?', hex: '#49B8C9', fonte: 'Ben 10' },
    { id: 22, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Chama?', hex: '#E35A2B', fonte: 'Ben 10' },
    { id: 23, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Massa Cinzenta?', hex: '#8A9A9B', fonte: 'Ben 10' },
    { id: 24, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Besta?', hex: '#B8A33A', fonte: 'Ben 10' },
    { id: 25, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Ultra T?', hex: '#252525', fonte: 'Ben 10' },
    { id: 26, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Cipó Selvagem?', hex: '#4B9B45', fonte: 'Ben 10' },
    { id: 27, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Fantasmático?', hex: '#A9D6C2', fonte: 'Ben 10' },
    { id: 28, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Mordecai?', hex: '#4A8DB8', fonte: 'Apenas um Show' },
    { id: 29, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Rigby?', hex: '#A86F3D', fonte: 'Apenas um Show' },
    { id: 30, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Musculoso?', hex: '#3E8B47', fonte: 'Apenas um Show' },
    { id: 31, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Jake?', hex: '#F2C84B', fonte: 'Hora de Aventura' },
    { id: 32, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da camisa de Finn?', hex: '#5A91C9', fonte: 'Hora de Aventura' },
    { id: 33, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do cabelo da Princesa Jujuba?', hex: '#E8A2C1', fonte: 'Hora de Aventura' },
    { id: 34, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo do Rei Gelado?', hex: '#5E82C1', fonte: 'Hora de Aventura' },
    { id: 35, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Gumball?', hex: '#5DA9D6', fonte: 'O Incrível Mundo de Gumball' },
    { id: 36, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Darwin?', hex: '#F29C38', fonte: 'O Incrível Mundo de Gumball' },
    { id: 37, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Anais?', hex: '#E88FA8', fonte: 'O Incrível Mundo de Gumball' },
    { id: 38, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do traje de Robin?', hex: '#273C72', fonte: 'Jovens Titãs' },
    { id: 39, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da pele de Ravena?', hex: '#6F5AA8', fonte: 'Jovens Titãs' },
    { id: 40, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da pele de Estelar?', hex: '#A85CB5', fonte: 'Jovens Titãs' },
    { id: 41, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da pele de Mutano?', hex: '#4DAF55', fonte: 'Jovens Titãs' },
    { id: 42, dificuldade: 'facil', pergunta: 'Qual é a cor predominante das partes metálicas de Cyborg?', hex: '#8D949A', fonte: 'Jovens Titãs' },
    { id: 43, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da camisa de Steven?', hex: '#E84C3D', fonte: 'Steven Universo' },
    { id: 44, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do cabelo de Steven?', hex: '#4A2B26', fonte: 'Steven Universo' },
    { id: 45, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa do Irmão do Jorel?', hex: '#E8A52B', fonte: 'Irmão do Jorel' },
    { id: 46, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do vestido da Lara?', hex: '#E6A5C0', fonte: 'Irmão do Jorel' },
    { id: 47, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Rex?', hex: '#273B63', fonte: 'Mutante Rex' },
    { id: 48, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Pops?', hex: '#F0B87A', fonte: 'Apenas um Show' },
    { id: 49, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Marceline?', hex: '#3A303F', fonte: 'Hora de Aventura' },
    { id: 50, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Insectóide?', hex: '#6E7A35', fonte: 'Ben 10' },
    { id: 51, dificuldade: 'media', pergunta: 'Qual é a cor predominante da gravata do Professor Utônio?', hex: '#D83A3A', fonte: 'As Meninas Superpoderosas' },
    { id: 52, dificuldade: 'media', pergunta: 'Qual é a cor predominante do vestido da Princesa Maisgrana?', hex: '#E8B23A', fonte: 'As Meninas Superpoderosas' },
    { id: 53, dificuldade: 'media', pergunta: 'Qual é a cor predominante do vestido de Dee Dee?', hex: '#E8A0C0', fonte: 'O Laboratório de Dexter' },
    { id: 54, dificuldade: 'media', pergunta: 'Qual é a cor predominante do vestido de Muriel?', hex: '#D88A48', fonte: 'Coragem, o Cão Covarde' },
    { id: 55, dificuldade: 'media', pergunta: 'Qual é a cor predominante do boné de Eddy?', hex: '#D9A92E', fonte: 'Du, Dudu e Edu' },
    { id: 56, dificuldade: 'media', pergunta: 'Qual é a cor predominante da túnica de Puro Osso?', hex: '#5D2F68', fonte: 'As Terríveis Aventuras de Billy e Mandy' },
    { id: 57, dificuldade: 'media', pergunta: 'Qual é a cor predominante dos óculos de Johnny Bravo?', hex: '#252525', fonte: 'Johnny Bravo' },
    { id: 58, dificuldade: 'media', pergunta: 'Qual é a cor predominante do cinto de Quatro Braços?', hex: '#27313A', fonte: 'Ben 10' },
    { id: 59, dificuldade: 'media', pergunta: 'Qual é a cor predominante das marcas no capacete de XLR8?', hex: '#F0B52B', fonte: 'Ben 10' },
    { id: 60, dificuldade: 'media', pergunta: 'Qual é a cor predominante dos cristais do corpo de Diamante?', hex: '#72D3DE', fonte: 'Ben 10' },
    { id: 61, dificuldade: 'media', pergunta: 'Qual é a cor predominante das chamas produzidas por Chama?', hex: '#F6A623', fonte: 'Ben 10' },
    { id: 62, dificuldade: 'media', pergunta: 'Qual é a cor predominante das linhas luminosas do corpo de Ultra T?', hex: '#6FCB3A', fonte: 'Ben 10' },
    { id: 63, dificuldade: 'media', pergunta: 'Qual é a cor predominante das plantas que formam o corpo de Cipó Selvagem?', hex: '#4B9B45', fonte: 'Ben 10' },
    { id: 64, dificuldade: 'media', pergunta: 'Qual é a cor predominante do corpo de Pairulito?', hex: '#5B8CC5', fonte: 'Apenas um Show' },
    { id: 65, dificuldade: 'media', pergunta: 'Qual é a cor predominante do corpo de Benson?', hex: '#C94B55', fonte: 'Apenas um Show' },
    { id: 66, dificuldade: 'media', pergunta: 'Qual é a cor predominante da pele da Princesa Caroço?', hex: '#B86AA7', fonte: 'Hora de Aventura' },
    { id: 67, dificuldade: 'media', pergunta: 'Qual é a cor predominante da guitarra de Marceline?', hex: '#9B2431', fonte: 'Hora de Aventura' },
    { id: 68, dificuldade: 'media', pergunta: 'Qual é a cor predominante do corpo de Nicole?', hex: '#5D83B3', fonte: 'O Incrível Mundo de Gumball' },
    { id: 69, dificuldade: 'media', pergunta: 'Qual é a cor predominante do corpo de Tobias?', hex: '#F0B34A', fonte: 'O Incrível Mundo de Gumball' },
    { id: 70, dificuldade: 'media', pergunta: 'Qual é a cor predominante da capa de Ravena?', hex: '#40306A', fonte: 'Jovens Titãs' },
    { id: 71, dificuldade: 'media', pergunta: 'Qual é a cor predominante do cabelo de Estelar?', hex: '#D84A35', fonte: 'Jovens Titãs' },
    { id: 72, dificuldade: 'media', pergunta: 'Qual é a cor predominante das partes mecânicas do corpo de Cyborg?', hex: '#4B5158', fonte: 'Jovens Titãs' },
    { id: 73, dificuldade: 'media', pergunta: 'Qual é a cor predominante da roupa de Lara?', hex: '#E6A5C0', fonte: 'Irmão do Jorel' },
    { id: 74, dificuldade: 'media', pergunta: 'Qual é a cor predominante do cabelo de Garnet?', hex: '#382C48', fonte: 'Steven Universo' },
    { id: 75, dificuldade: 'media', pergunta: 'Qual é a cor predominante do cabelo de Pérola?', hex: '#F2B5C4', fonte: 'Steven Universo' },
    { id: 76, dificuldade: 'media', pergunta: 'Qual é a cor predominante do cabelo de Ametista?', hex: '#8B4D9B', fonte: 'Steven Universo' },
    { id: 77, dificuldade: 'media', pergunta: 'Qual é a cor predominante das partes mecânicas de Rex?', hex: '#87929B', fonte: 'Mutante Rex' },
    { id: 78, dificuldade: 'media', pergunta: 'Qual é a cor predominante dos olhos de Besta?', hex: '#E5A92F', fonte: 'Ben 10' },
    { id: 79, dificuldade: 'media', pergunta: 'Qual é a cor predominante do símbolo do Omnitrix em Fantasmático?', hex: '#8BCBBA', fonte: 'Ben 10' },
    { id: 80, dificuldade: 'media', pergunta: 'Qual é a cor predominante dos olhos de Insectóide?', hex: '#D8D04A', fonte: 'Ben 10' },
    { id: 81, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do pelo do Macaco Louco em sua forma original?', hex: '#704B91', fonte: 'As Meninas Superpoderosas' },
    { id: 82, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do laço de Dee Dee?', hex: '#E77AAE', fonte: 'O Laboratório de Dexter' },
    { id: 83, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do chapéu de Eustácio?', hex: '#B86F3D', fonte: 'Coragem, o Cão Covarde' },
    { id: 84, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da foice de Puro Osso?', hex: '#70777D', fonte: 'As Terríveis Aventuras de Billy e Mandy' },
    { id: 85, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante das faixas no corpo de Quatro Braços?', hex: '#D6A12F', fonte: 'Ben 10' },
    { id: 86, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da viseira de XLR8?', hex: '#D9B83E', fonte: 'Ben 10' },
    { id: 87, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante dos detalhes do uniforme de Diamante?', hex: '#294C68', fonte: 'Ben 10' },
    { id: 88, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante das pedras que aparecem na cabeça de Chama?', hex: '#5B3028', fonte: 'Ben 10' },
    { id: 89, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante das linhas que percorrem o corpo de Ultra T?', hex: '#6FCB3A', fonte: 'Ben 10' },
    { id: 90, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante das asas de Pairulito?', hex: '#6AA5D8', fonte: 'Apenas um Show' },
    { id: 91, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da guitarra de Marceline?', hex: '#9B2431', fonte: 'Hora de Aventura' },
    { id: 92, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante dos olhos de Gumball?', hex: '#65B8D4', fonte: 'O Incrível Mundo de Gumball' },
    { id: 93, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante dos olhos de Ravena?', hex: '#4A2E67', fonte: 'Jovens Titãs' },
    { id: 94, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da roupa de Pérola?', hex: '#B8D7D2', fonte: 'Steven Universo' },
    { id: 95, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da roupa de Garnet?', hex: '#4C315B', fonte: 'Steven Universo' },
    { id: 96, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da roupa de Ametista?', hex: '#6C3E7B', fonte: 'Steven Universo' },
    { id: 97, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da energia produzida pelas máquinas de Rex?', hex: '#4DB6C7', fonte: 'Mutante Rex' },
    { id: 98, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante das sementes explosivas de Cipó Selvagem?', hex: '#C7A52A', fonte: 'Ben 10' },
    { id: 99, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante dos detalhes do corpo de Fantasmático?', hex: '#6D8F82', fonte: 'Ben 10' },
    { id: 100, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante das asas de Insectóide?', hex: '#6E7A35', fonte: 'Ben 10' },
  ],
  nickelodeon: [
    { id: 1, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo de Bob Esponja?', hex: '#F2D52E', fonte: 'Bob Esponja Calça Quadrada' },
    { id: 2, dificuldade: 'facil', pergunta: 'Qual é a cor da gravata de Bob Esponja?', hex: '#C62828', fonte: 'Bob Esponja Calça Quadrada' },
    { id: 3, dificuldade: 'facil', pergunta: 'Qual é a cor da calça de Bob Esponja?', hex: '#8A6339', fonte: 'Bob Esponja Calça Quadrada' },
    { id: 4, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo de Patrick?', hex: '#F28CA8', fonte: 'Bob Esponja Calça Quadrada' },
    { id: 5, dificuldade: 'facil', pergunta: 'Qual é a cor da bermuda de Patrick?', hex: '#72A95A', fonte: 'Bob Esponja Calça Quadrada' },
    { id: 6, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo de Lula Molusco?', hex: '#8BB5A5', fonte: 'Bob Esponja Calça Quadrada' },
    { id: 7, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo de Sandy?', hex: '#B88652', fonte: 'Bob Esponja Calça Quadrada' },
    { id: 8, dificuldade: 'facil', pergunta: 'Qual é a cor do uniforme de Sandy?', hex: '#6B9EBD', fonte: 'Bob Esponja Calça Quadrada' },
    { id: 9, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Gary?', hex: '#91A9B7', fonte: 'Bob Esponja Calça Quadrada' },
    { id: 10, dificuldade: 'facil', pergunta: 'Qual é a cor da casca de Plankton?', hex: '#2F9E44', fonte: 'Bob Esponja Calça Quadrada' },
    { id: 11, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo de Timmy?', hex: '#7A4A2B', fonte: 'Os Padrinhos Mágicos' },
    { id: 12, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo de Cosmo?', hex: '#6BCB5E', fonte: 'Os Padrinhos Mágicos' },
    { id: 13, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo de Wanda?', hex: '#F08AA4', fonte: 'Os Padrinhos Mágicos' },
    { id: 14, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo de Wanda?', hex: '#8E62B5', fonte: 'Os Padrinhos Mágicos' },
    { id: 15, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Timmy?', hex: '#8A55A6', fonte: 'Os Padrinhos Mágicos' },
    { id: 16, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Vicky?', hex: '#E64A35', fonte: 'Os Padrinhos Mágicos' },
    { id: 17, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo de Jimmy?', hex: '#7A4A2B', fonte: 'Jimmy Neutron' },
    { id: 18, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da camisa de Jimmy?', hex: '#D94B3D', fonte: 'Jimmy Neutron' },
    { id: 19, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Carl?', hex: '#6DA7C8', fonte: 'Jimmy Neutron' },
    { id: 20, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Sheen?', hex: '#4A9B55', fonte: 'Jimmy Neutron' },
    { id: 21, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo de Cindy?', hex: '#F0D2A2', fonte: 'Jimmy Neutron' },
    { id: 22, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Cindy?', hex: '#8B5AA8', fonte: 'Jimmy Neutron' },
    { id: 23, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Aang?', hex: '#D8A33A', fonte: 'Avatar: A Lenda de Aang' },
    { id: 24, dificuldade: 'facil', pergunta: 'Qual é a cor das tatuagens de Aang?', hex: '#5C86B2', fonte: 'Avatar: A Lenda de Aang' },
    { id: 25, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Katara?', hex: '#3C75A8', fonte: 'Avatar: A Lenda de Aang' },
    { id: 26, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Sokka?', hex: '#536E8A', fonte: 'Avatar: A Lenda de Aang' },
    { id: 27, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Zuko?', hex: '#9B382C', fonte: 'Avatar: A Lenda de Aang' },
    { id: 28, dificuldade: 'facil', pergunta: 'Qual é a cor do cabelo de Azula?', hex: '#171717', fonte: 'Avatar: A Lenda de Aang' },
    { id: 29, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Toph?', hex: '#8A6A45', fonte: 'Avatar: A Lenda de Aang' },
    { id: 30, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do pelo de Appa?', hex: '#B58A55', fonte: 'Avatar: A Lenda de Aang' },
    { id: 31, dificuldade: 'facil', pergunta: 'Qual é a cor da máscara de Leonardo?', hex: '#2474C6', fonte: 'Tartarugas Ninja' },
    { id: 32, dificuldade: 'facil', pergunta: 'Qual é a cor da máscara de Raphael?', hex: '#D52B32', fonte: 'Tartarugas Ninja' },
    { id: 33, dificuldade: 'facil', pergunta: 'Qual é a cor da máscara de Donatello?', hex: '#7447A8', fonte: 'Tartarugas Ninja' },
    { id: 34, dificuldade: 'facil', pergunta: 'Qual é a cor da máscara de Michelangelo?', hex: '#E89A2F', fonte: 'Tartarugas Ninja' },
    { id: 35, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo das Tartarugas Ninja?', hex: '#4C9B54', fonte: 'Tartarugas Ninja' },
    { id: 36, dificuldade: 'facil', pergunta: "Qual é a cor predominante da roupa de April O'Neil?", hex: '#E4C12E', fonte: 'Tartarugas Ninja' },
    { id: 37, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do pelo de Po?', hex: '#252525', fonte: 'Kung Fu Panda' },
    { id: 38, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Po?', hex: '#7A9B49', fonte: 'Kung Fu Panda' },
    { id: 39, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do pelo de Tigresa?', hex: '#D8A338', fonte: 'Kung Fu Panda' },
    { id: 40, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Mestre Shifu?', hex: '#A34B3B', fonte: 'Kung Fu Panda' },
    { id: 41, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Kowalski?', hex: '#30353A', fonte: 'Os Pinguins de Madagascar' },
    { id: 42, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do bico de Rico?', hex: '#E3A72F', fonte: 'Os Pinguins de Madagascar' },
    { id: 43, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Rei Julien?', hex: '#A7A88B', fonte: 'Os Pinguins de Madagascar' },
    { id: 44, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da cauda de Rei Julien?', hex: '#D5A84A', fonte: 'Os Pinguins de Madagascar' },
    { id: 45, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de B.O.B.?', hex: '#74A9C4', fonte: 'Monstros vs. Alienígenas' },
    { id: 46, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Susan?', hex: '#79A5D1', fonte: 'Monstros vs. Alienígenas' },
    { id: 47, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do corpo de Dr. Barata?', hex: '#65743E', fonte: 'Monstros vs. Alienígenas' },
    { id: 48, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da camisa de Phineas?', hex: '#E85A35', fonte: 'Phineas e Ferb' },
    { id: 49, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da roupa de Ferb?', hex: '#6D8B55', fonte: 'Phineas e Ferb' },
    { id: 50, dificuldade: 'facil', pergunta: 'Qual é a cor do corpo de Perry?', hex: '#6E9A48', fonte: 'Phineas e Ferb' },
    { id: 51, dificuldade: 'media', pergunta: 'Qual é a cor da gravata de Patrick?', hex: '#C94A3A', fonte: 'Bob Esponja Calça Quadrada' },
    { id: 52, dificuldade: 'media', pergunta: 'Qual é a cor predominante do uniforme do Sr. Siriguejo?', hex: '#2F7A4A', fonte: 'Bob Esponja Calça Quadrada' },
    { id: 53, dificuldade: 'media', pergunta: 'Qual é a cor predominante da roupa de Cosmo?', hex: '#BBD5E5', fonte: 'Os Padrinhos Mágicos' },
    { id: 54, dificuldade: 'media', pergunta: 'Qual é a cor predominante da roupa de Wanda?', hex: '#E5B6C9', fonte: 'Os Padrinhos Mágicos' },
    { id: 55, dificuldade: 'media', pergunta: 'Qual é a cor predominante dos óculos de Carl?', hex: '#6B4A35', fonte: 'Jimmy Neutron' },
    { id: 56, dificuldade: 'media', pergunta: 'Qual é a cor predominante da roupa de Libby?', hex: '#D64E5A', fonte: 'Jimmy Neutron' },
    { id: 57, dificuldade: 'media', pergunta: 'Qual é a cor predominante da roupa de Iroh?', hex: '#B84B32', fonte: 'Avatar: A Lenda de Aang' },
    { id: 58, dificuldade: 'media', pergunta: 'Qual é a cor predominante do traje de combate de Suki?', hex: '#5B7D50', fonte: 'Avatar: A Lenda de Aang' },
    { id: 59, dificuldade: 'media', pergunta: 'Qual é a cor predominante da roupa de Mai?', hex: '#3A3A4B', fonte: 'Avatar: A Lenda de Aang' },
    { id: 60, dificuldade: 'media', pergunta: 'Qual é a cor predominante da roupa de Ty Lee?', hex: '#D85B4A', fonte: 'Avatar: A Lenda de Aang' },
    { id: 61, dificuldade: 'media', pergunta: 'Qual é a cor predominante do bastão de Donatello?', hex: '#8A5B35', fonte: 'Tartarugas Ninja' },
    { id: 62, dificuldade: 'media', pergunta: 'Qual é a cor predominante das espadas de Leonardo?', hex: '#7B858A', fonte: 'Tartarugas Ninja' },
    { id: 63, dificuldade: 'media', pergunta: 'Qual é a cor predominante das armas de Michelangelo?', hex: '#9B6A42', fonte: 'Tartarugas Ninja' },
    { id: 64, dificuldade: 'media', pergunta: 'Qual é a cor predominante do bastão de Mestre Shifu?', hex: '#8A5A35', fonte: 'Kung Fu Panda' },
    { id: 65, dificuldade: 'media', pergunta: 'Qual é a cor predominante da roupa de Mestre Oogway?', hex: '#6B8A43', fonte: 'Kung Fu Panda' },
    { id: 66, dificuldade: 'media', pergunta: 'Qual é a cor predominante do corpo de Skipper?', hex: '#34393D', fonte: 'Os Pinguins de Madagascar' },
    { id: 67, dificuldade: 'media', pergunta: 'Qual é a cor predominante do corpo de Private?', hex: '#555B5F', fonte: 'Os Pinguins de Madagascar' },
    { id: 68, dificuldade: 'media', pergunta: 'Qual é a cor predominante do traje de Gallaxhar?', hex: '#5B397A', fonte: 'Monstros vs. Alienígenas' },
    { id: 69, dificuldade: 'media', pergunta: 'Qual é a cor predominante do vestido de Susan?', hex: '#6B82C1', fonte: 'Monstros vs. Alienígenas' },
    { id: 70, dificuldade: 'media', pergunta: 'Qual é a cor predominante da roupa de Candace?', hex: '#D94B4B', fonte: 'Phineas e Ferb' },
    { id: 71, dificuldade: 'media', pergunta: 'Qual é a cor predominante da roupa de Isabella?', hex: '#E7A52F', fonte: 'Phineas e Ferb' },
    { id: 72, dificuldade: 'media', pergunta: 'Qual é a cor predominante da roupa de Buford?', hex: '#6A82A5', fonte: 'Phineas e Ferb' },
    { id: 73, dificuldade: 'media', pergunta: 'Qual é a cor predominante da roupa de Baljeet?', hex: '#4C8C63', fonte: 'Phineas e Ferb' },
    { id: 74, dificuldade: 'media', pergunta: 'Qual é a cor predominante do chapéu de Perry?', hex: '#A87B35', fonte: 'Phineas e Ferb' },
    { id: 75, dificuldade: 'media', pergunta: 'Qual é a cor predominante da roupa do Dr. Doofenshmirtz?', hex: '#7866A8', fonte: 'Phineas e Ferb' },
    { id: 76, dificuldade: 'media', pergunta: 'Qual é a cor predominante da casa de Patrick?', hex: '#E58B9D', fonte: 'Bob Esponja Calça Quadrada' },
    { id: 77, dificuldade: 'media', pergunta: 'Qual é a cor predominante da roupa de Chester?', hex: '#4A78B2', fonte: 'Os Padrinhos Mágicos' },
    { id: 78, dificuldade: 'media', pergunta: 'Qual é a cor predominante da roupa de Goddard?', hex: '#4A83B7', fonte: 'Jimmy Neutron' },
    { id: 79, dificuldade: 'media', pergunta: 'Qual é a cor predominante do traje de Destruidor?', hex: '#555B65', fonte: 'Jimmy Neutron' },
    { id: 80, dificuldade: 'media', pergunta: 'Qual é a cor predominante do pelo de Tai Lung?', hex: '#A8A4A1', fonte: 'Kung Fu Panda' },
    { id: 81, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da gravata usada pelo Sr. Siriguejo?', hex: '#6B3D91', fonte: 'Bob Esponja Calça Quadrada' },
    { id: 82, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da casa de Lula Molusco?', hex: '#A86C8D', fonte: 'Bob Esponja Calça Quadrada' },
    { id: 83, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da coroa de Rei Vicky?', hex: '#E2B536', fonte: 'Os Padrinhos Mágicos' },
    { id: 84, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do cabelo de Hugh Neutron?', hex: '#A8733D', fonte: 'Jimmy Neutron' },
    { id: 85, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da roupa de Avatar Roku?', hex: '#A84C35', fonte: 'Avatar: A Lenda de Aang' },
    { id: 86, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante das roupas de Mestre Pakku?', hex: '#476E98', fonte: 'Avatar: A Lenda de Aang' },
    { id: 87, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da faixa usada por Splinter?', hex: '#9B6A3E', fonte: 'Tartarugas Ninja' },
    { id: 88, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da armadura usada por Lord Shen?', hex: '#8D8C91', fonte: 'Kung Fu Panda' },
    { id: 89, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da coroa usada por Rei Julien?', hex: '#D4A52E', fonte: 'Os Pinguins de Madagascar' },
    { id: 90, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do uniforme usado pelo General W.R. Monger?', hex: '#4A5663', fonte: 'Monstros vs. Alienígenas' },
    { id: 91, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do vestido usado por Linda Flynn-Fletcher?', hex: '#D96C3B', fonte: 'Phineas e Ferb' },
    { id: 92, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do uniforme de Major Monogram?', hex: '#4E6B52', fonte: 'Phineas e Ferb' },
    { id: 93, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da roupa de Jeremy?', hex: '#5D79A4', fonte: 'Phineas e Ferb' },
    { id: 94, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do chapéu usado por Ferb?', hex: '#D5A83A', fonte: 'Phineas e Ferb' },
    { id: 95, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do pelo de Perry quando ele está caracterizado como agente?', hex: '#5B8F45', fonte: 'Phineas e Ferb' },
    { id: 96, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do traje de combate de Zuko?', hex: '#25252B', fonte: 'Avatar: A Lenda de Aang' },
    { id: 97, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do traje usado por Casey Jones?', hex: '#66727A', fonte: 'Tartarugas Ninja' },
    { id: 98, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da roupa de Mestre Croc?', hex: '#5B7D62', fonte: 'Kung Fu Panda' },
    { id: 99, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do pelo de Mort?', hex: '#B9A98A', fonte: 'Os Pinguins de Madagascar' },
    { id: 100, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do corpo de The Missing Link?', hex: '#4E9A96', fonte: 'Monstros vs. Alienígenas' },
  ],
  marcas: [
    { id: 1, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da identidade visual da Coca-Cola?', hex: '#E41E2B', fonte: 'Coca-Cola' },
    { id: 2, dificuldade: 'facil', pergunta: 'Qual é a cor predominante dos famosos arcos do McDonald\'s?', hex: '#FFC72C', fonte: "McDonald's" },
    { id: 3, dificuldade: 'facil', pergunta: 'Qual é a cor mais tradicional do símbolo Swoosh da Nike?', hex: '#111111', fonte: 'Nike' },
    { id: 4, dificuldade: 'facil', pergunta: 'Qual é a cor mais associada ao símbolo clássico da Apple em versões monocromáticas?', hex: '#000000', fonte: 'Apple' },
    { id: 5, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da primeira letra do logotipo do Google?', hex: '#4285F4', fonte: 'Google' },
    { id: 6, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do símbolo de reprodução do YouTube?', hex: '#FF0000', fonte: 'YouTube' },
    { id: 7, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do fundo do ícone tradicional do Instagram?', hex: '#C13584', fonte: 'Instagram' },
    { id: 8, dificuldade: 'facil', pergunta: 'Qual é a cor predominante associada ao ícone do Facebook?', hex: '#1877F2', fonte: 'Facebook' },
    { id: 9, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do ícone do WhatsApp?', hex: '#25D366', fonte: 'WhatsApp' },
    { id: 10, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do símbolo do Spotify?', hex: '#1DB954', fonte: 'Spotify' },
    { id: 11, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da letra N usada pela Netflix?', hex: '#E50914', fonte: 'Netflix' },
    { id: 12, dificuldade: 'facil', pergunta: 'Qual é a cor da seta característica abaixo do nome Amazon?', hex: '#FF9900', fonte: 'Amazon' },
    { id: 13, dificuldade: 'facil', pergunta: 'Qual é a cor predominante de um dos quadrados do símbolo da Microsoft?', hex: '#F25022', fonte: 'Microsoft' },
    { id: 14, dificuldade: 'facil', pergunta: 'Qual é a cor mais associada ao símbolo tradicional do Windows?', hex: '#0078D4', fonte: 'Windows' },
    { id: 15, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da parte superior do círculo da Pepsi?', hex: '#E32934', fonte: 'Pepsi' },
    { id: 16, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da estrela no logotipo da Heineken?', hex: '#E30613', fonte: 'Heineken' },
    { id: 17, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do círculo que envolve a sereia da Starbucks?', hex: '#00704A', fonte: 'Starbucks' },
    { id: 18, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do pão representado no logotipo do Burger King?', hex: '#F5B335', fonte: 'Burger King' },
    { id: 19, dificuldade: 'facil', pergunta: 'Qual é a cor predominante usada na identidade visual do KFC?', hex: '#F40027', fonte: 'KFC' },
    { id: 20, dificuldade: 'facil', pergunta: 'Qual é a cor mais tradicional das três listras da Adidas?', hex: '#000000', fonte: 'Adidas' },
    { id: 21, dificuldade: 'facil', pergunta: 'Qual é a cor mais tradicional do felino no logotipo da Puma?', hex: '#000000', fonte: 'Puma' },
    { id: 22, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do fundo do logotipo da LEGO?', hex: '#D01012', fonte: 'LEGO' },
    { id: 23, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do logotipo clássico da Nintendo?', hex: '#E60012', fonte: 'Nintendo' },
    { id: 24, dificuldade: 'facil', pergunta: 'Qual é a cor tradicionalmente associada ao símbolo do PlayStation?', hex: '#003791', fonte: 'PlayStation' },
    { id: 25, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do símbolo do Xbox?', hex: '#107C10', fonte: 'Xbox' },
    { id: 26, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do fundo do brasão tradicional da Ferrari?', hex: '#FFF200', fonte: 'Ferrari' },
    { id: 27, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do fundo do escudo da Lamborghini?', hex: '#000000', fonte: 'Lamborghini' },
    { id: 28, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do cavalo no brasão da Porsche?', hex: '#000000', fonte: 'Porsche' },
    { id: 29, dificuldade: 'facil', pergunta: 'Qual é a cor tradicionalmente usada no símbolo de três pontas da Mercedes-Benz?', hex: '#000000', fonte: 'Mercedes-Benz' },
    { id: 30, dificuldade: 'facil', pergunta: 'Qual é a cor de uma das quatro partes centrais do símbolo da BMW?', hex: '#0066B1', fonte: 'BMW' },
    { id: 31, dificuldade: 'facil', pergunta: 'Qual é a cor tradicionalmente associada ao símbolo da Volkswagen?', hex: '#003B7A', fonte: 'Volkswagen' },
    { id: 32, dificuldade: 'facil', pergunta: 'Qual é a cor mais tradicional do símbolo da Toyota?', hex: '#EB0A1E', fonte: 'Toyota' },
    { id: 33, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da concha no logotipo da Shell?', hex: '#FFD500', fonte: 'Shell' },
    { id: 34, dificuldade: 'facil', pergunta: 'Qual é a cor predominante dos dois touros no logotipo da Red Bull?', hex: '#CC0000', fonte: 'Red Bull' },
    { id: 35, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da identidade visual clássica da Fanta?', hex: '#F58220', fonte: 'Fanta' },
    { id: 36, dificuldade: 'facil', pergunta: 'Qual é a cor predominante associada à identidade visual da Sprite?', hex: '#00A651', fonte: 'Sprite' },
    { id: 37, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da faixa externa do logotipo clássico da Oreo?', hex: '#003DA5', fonte: 'Oreo' },
    { id: 38, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da embalagem clássica do KitKat?', hex: '#E30613', fonte: 'KitKat' },
    { id: 39, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do cabelo do personagem do logotipo da Pringles?', hex: '#6B3F2A', fonte: 'Pringles' },
    { id: 40, dificuldade: 'facil', pergunta: 'Qual é a cor tradicional do personagem vermelho da M&M\'s?', hex: '#ED1C24', fonte: "M&M's" },
    { id: 41, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da identidade visual tradicional da Doritos?', hex: '#F58220', fonte: 'Doritos' },
    { id: 42, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da parte superior do logotipo da Nutella?', hex: '#E30613', fonte: 'Nutella' },
    { id: 43, dificuldade: 'facil', pergunta: 'Qual é a cor predominante da identidade visual da Colgate?', hex: '#E31837', fonte: 'Colgate' },
    { id: 44, dificuldade: 'facil', pergunta: 'Qual é a cor tradicionalmente associada ao símbolo da pomba da Dove?', hex: '#C5A572', fonte: 'Dove' },
    { id: 45, dificuldade: 'facil', pergunta: 'Qual é a cor predominante tradicional da identidade visual da Gillette?', hex: '#0055A5', fonte: 'Gillette' },
    { id: 46, dificuldade: 'facil', pergunta: 'Qual é a cor mais associada ao logotipo tradicional da Samsung?', hex: '#1428A0', fonte: 'Samsung' },
    { id: 47, dificuldade: 'facil', pergunta: 'Qual é a cor mais tradicional do logotipo da Sony?', hex: '#000000', fonte: 'Sony' },
    { id: 48, dificuldade: 'facil', pergunta: 'Qual é a cor predominante do círculo que forma o símbolo da LG?', hex: '#A50034', fonte: 'LG' },
    { id: 49, dificuldade: 'facil', pergunta: 'Qual é a cor tradicional do logotipo da Canon?', hex: '#C00000', fonte: 'Canon' },
    { id: 50, dificuldade: 'facil', pergunta: 'Qual é a cor predominante de um dos efeitos de sombra do símbolo do TikTok?', hex: '#25F4EE', fonte: 'TikTok' },
    { id: 51, dificuldade: 'media', pergunta: 'Qual é a cor predominante associada à identidade visual do Claude?', hex: '#D97757', fonte: 'Claude' },
    { id: 52, dificuldade: 'media', pergunta: 'Qual é a cor predominante do símbolo do Discord?', hex: '#5865F2', fonte: 'Discord' },
    { id: 53, dificuldade: 'media', pergunta: 'Qual é a cor predominante da identidade visual da Twitch?', hex: '#9146FF', fonte: 'Twitch' },
    { id: 54, dificuldade: 'media', pergunta: 'Qual é a cor predominante do círculo que envolve o avião de papel do Telegram?', hex: '#229ED9', fonte: 'Telegram' },
    { id: 55, dificuldade: 'media', pergunta: 'Qual é a cor predominante do quadrado que envolve o símbolo do LinkedIn?', hex: '#0A66C2', fonte: 'LinkedIn' },
    { id: 56, dificuldade: 'media', pergunta: 'Qual é a cor tradicional do símbolo Bélo do Airbnb?', hex: '#FF5A5F', fonte: 'Airbnb' },
    { id: 57, dificuldade: 'media', pergunta: 'Qual é a cor predominante da identidade visual atual da Uber?', hex: '#000000', fonte: 'Uber' },
    { id: 58, dificuldade: 'media', pergunta: 'Qual é a cor predominante da identidade visual do iFood?', hex: '#EA1D2C', fonte: 'iFood' },
    { id: 59, dificuldade: 'media', pergunta: 'Qual é a cor predominante do fundo do logotipo do Mercado Livre?', hex: '#FFE600', fonte: 'Mercado Livre' },
    { id: 60, dificuldade: 'media', pergunta: 'Qual é a cor mais característica da identidade visual do Nubank?', hex: '#820AD1', fonte: 'Nubank' },
    { id: 61, dificuldade: 'media', pergunta: 'Qual é a cor predominante da identidade visual do Itaú?', hex: '#EC7000', fonte: 'Itaú' },
    { id: 62, dificuldade: 'media', pergunta: 'Qual é a cor predominante da identidade visual do Bradesco?', hex: '#CC092F', fonte: 'Bradesco' },
    { id: 63, dificuldade: 'media', pergunta: 'Qual é a cor predominante do símbolo tradicional do Banco do Brasil?', hex: '#F9D616', fonte: 'Banco do Brasil' },
    { id: 64, dificuldade: 'media', pergunta: 'Qual é a cor tradicionalmente associada ao logotipo da Havaianas?', hex: '#0088C2', fonte: 'Havaianas' },
    { id: 65, dificuldade: 'media', pergunta: 'Qual é a cor predominante tradicionalmente associada ao logotipo do O Boticário?', hex: '#007E5B', fonte: 'O Boticário' },
    { id: 66, dificuldade: 'media', pergunta: 'Qual é a cor predominante do círculo externo do símbolo tradicional da Globo?', hex: '#008FD5', fonte: 'Globo' },
    { id: 67, dificuldade: 'media', pergunta: 'Qual é a cor predominante de um dos círculos do logotipo da Mastercard?', hex: '#EB001B', fonte: 'Mastercard' },
    { id: 68, dificuldade: 'media', pergunta: 'Qual é a cor predominante tradicionalmente associada ao logotipo da Visa?', hex: '#1A1F71', fonte: 'Visa' },
    { id: 69, dificuldade: 'media', pergunta: 'Qual é a cor predominante tradicional do símbolo do PayPal?', hex: '#003087', fonte: 'PayPal' },
    { id: 70, dificuldade: 'media', pergunta: 'Qual é a cor predominante tradicionalmente associada à identidade visual da Intel?', hex: '#0068B5', fonte: 'Intel' },
    { id: 71, dificuldade: 'media', pergunta: 'Qual é a cor predominante tradicional da identidade visual da GoPro?', hex: '#00AEEF', fonte: 'GoPro' },
    { id: 72, dificuldade: 'media', pergunta: 'Qual é a cor predominante tradicional da identidade visual da Nescafé?', hex: '#D71920', fonte: 'Nescafé' },
    { id: 73, dificuldade: 'media', pergunta: 'Qual é a cor predominante da identidade visual da Heinz?', hex: '#D2232A', fonte: 'Heinz' },
    { id: 74, dificuldade: 'media', pergunta: 'Qual é a cor predominante da identidade visual clássica da Ruffles?', hex: '#E31837', fonte: 'Ruffles' },
    { id: 75, dificuldade: 'media', pergunta: 'Qual é a cor predominante do círculo central do logotipo da Lay\'s?', hex: '#FFD900', fonte: "Lay's" },
    { id: 76, dificuldade: 'media', pergunta: 'Qual é a cor predominante de uma das setas do logotipo da Subway?', hex: '#008C45', fonte: 'Subway' },
    { id: 77, dificuldade: 'media', pergunta: 'Qual é a cor predominante de uma das partes do dominó da Domino\'s?', hex: '#E31837', fonte: "Domino's" },
    { id: 78, dificuldade: 'media', pergunta: 'Qual é a cor predominante tradicional do símbolo da Pizza Hut?', hex: '#EE3124', fonte: 'Pizza Hut' },
    { id: 79, dificuldade: 'media', pergunta: 'Qual é a cor predominante tradicional da identidade visual da Popeyes?', hex: '#F58220', fonte: 'Popeyes' },
    { id: 80, dificuldade: 'media', pergunta: 'Qual é a cor tradicional do crocodilo do logotipo da Lacoste?', hex: '#006B3F', fonte: 'Lacoste' },
    { id: 81, dificuldade: 'dificil', pergunta: 'Qual é a cor tradicionalmente associada à estrela do símbolo clássico da Converse?', hex: '#000000', fonte: 'Converse' },
    { id: 82, dificuldade: 'dificil', pergunta: 'Qual é a cor tradicionalmente usada no logotipo da Vans?', hex: '#D71920', fonte: 'Vans' },
    { id: 83, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante tradicional do símbolo da New Balance?', hex: '#C8102E', fonte: 'New Balance' },
    { id: 84, dificuldade: 'dificil', pergunta: 'Qual é a cor tradicional do logotipo da Ray-Ban?', hex: '#E31B23', fonte: 'Ray-Ban' },
    { id: 85, dificuldade: 'dificil', pergunta: 'Qual é a cor tradicional da coroa no logotipo da Rolex?', hex: '#006039', fonte: 'Rolex' },
    { id: 86, dificuldade: 'dificil', pergunta: 'Qual é a cor tradicionalmente usada no triângulo do logotipo da Prada?', hex: '#000000', fonte: 'Prada' },
    { id: 87, dificuldade: 'dificil', pergunta: 'Qual é a cor tradicionalmente associada ao símbolo de duas letras G da Gucci?', hex: '#000000', fonte: 'Gucci' },
    { id: 88, dificuldade: 'dificil', pergunta: 'Qual é a cor tradicional das duas letras C entrelaçadas da Chanel?', hex: '#000000', fonte: 'Chanel' },
    { id: 89, dificuldade: 'dificil', pergunta: 'Qual é a cor tradicionalmente associada ao monograma LV clássico?', hex: '#5B351F', fonte: 'Louis Vuitton' },
    { id: 90, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do fundo do logotipo da DHL?', hex: '#FFCC00', fonte: 'DHL' },
    { id: 91, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante da primeira parte do nome no logotipo clássico da FedEx?', hex: '#4D148C', fonte: 'FedEx' },
    { id: 92, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante tradicional do símbolo dos Correios?', hex: '#F5C400', fonte: 'Correios' },
    { id: 93, dificuldade: 'dificil', pergunta: 'Qual é a cor tradicionalmente associada ao logotipo da HBO?', hex: '#000000', fonte: 'HBO' },
    { id: 94, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante tradicionalmente usada na identidade visual do Disney+?', hex: '#113CCF', fonte: 'Disney+' },
    { id: 95, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do símbolo do Steam?', hex: '#171A21', fonte: 'Steam' },
    { id: 96, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do círculo que representa o YouTube Music?', hex: '#FF0000', fonte: 'YouTube Music' },
    { id: 97, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante de uma das partes do símbolo triangular do Google Play?', hex: '#34A853', fonte: 'Google Play' },
    { id: 98, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante de uma das três partes externas do símbolo do Google Chrome?', hex: '#DB4437', fonte: 'Google Chrome' },
    { id: 99, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante tradicional da identidade visual da Nikon?', hex: '#FFCC00', fonte: 'Nikon' },
    { id: 100, dificuldade: 'dificil', pergunta: 'Qual é a cor predominante do segundo círculo do símbolo clássico da Mastercard?', hex: '#F79E1B', fonte: 'Mastercard' },
  ],
};
